#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
html-album.py — HTML Fotoalbum Generator
Genereert een HTML-album vergelijkbaar met alm.agrarix.net

Vereisten:
    pip install Pillow

Gebruik:
    python html-album.py
    (leest html-album.json in dezelfde map)
"""

import argparse
import json
import os
import platform
import re
import shutil
import socket
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Union

# Forceer UTF-8 output zodat cmd/PowerShell niet crasht op speciale tekens
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Programma details voor de footer
PGM = "html-album"
VERSION = "v2 (08-09-2026 20:33)"

# === START FOOTER DEFINITIE ===
# Bepaal OS en hostname voor de footer
try:
    _hostname = socket.gethostname().split(".")[0]
except Exception:
    _hostname = ""
_os_naam = "Windows" if sys.platform == "win32" else "Linux"

_default_footer = f"Generated by ${{PGM}} ${{VER}} ({_os_naam})"
if sys.platform != "win32":
    _default_footer += f" at {_hostname}"
# === END FOOTER DEFINITIE ===

def safe_copy(src: Path, dst: Path) -> None:
    """Kopieert een bestand. Probeert metadata te behouden (copy2), maar valt terug op copyfile bij OS-fouten (zoals op netwerkshares)."""
    try:
        shutil.copy2(src, dst)
    except OSError:
        shutil.copyfile(src, dst)

def is_file_writable(path: Path) -> bool:
    """Controleert of een bestand herschrijfbaar is (niet ReadOnly / schrijfbeveiligd)."""
    if path.exists():
        if not os.access(path, os.W_OK):
            return False
        try:
            with open(path, "a", encoding="utf-8"):
                pass
            return True
        except (PermissionError, OSError):
            return False
    else:
        # Als het bestand nog niet bestaat, controleer of de bovenliggende map beschrijfbaar is
        parent = path.parent
        while not parent.exists() and parent != parent.parent:
            parent = parent.parent
        return os.access(parent, os.W_OK)



# ---------------------------------------------------------------------------
# Pillow (voor thumbnails)
# ---------------------------------------------------------------------------
from contextlib import contextmanager
import tempfile

try:
    from PIL import Image, ExifTags, ImageOps
    HAS_PIL = True
except ImportError:
    HAS_PIL = False

try:
    import pillow_heif
    pillow_heif.register_heif_opener()
    HAS_HEIF = True
except ImportError:
    HAS_HEIF = False

@contextmanager
def safe_image_open(img_path: Path):
    """Context manager die een afbeelding opent. Kopieert naar een lokaal temp-bestand als direct openen faalt (bijv. door CIFS memory issues)."""
    temp_path = None
    try:
        img = Image.open(img_path)
        img.load()
        img.close()
        img = Image.open(img_path)
        try:
            yield img
        finally:
            img.close()
    except Exception as e:
        try:
            temp_dir = Path("/tmp") if Path("/tmp").exists() else Path(tempfile.gettempdir())
            with tempfile.NamedTemporaryFile(dir=temp_dir, suffix=img_path.suffix, delete=False) as tmp:
                temp_path = Path(tmp.name)
            
            shutil.copy2(img_path, temp_path)
            
            img = Image.open(temp_path)
            img.load()
            try:
                yield img
            finally:
                img.close()
                try:
                    temp_path.unlink()
                except Exception:
                    pass
        except Exception:
            if temp_path and temp_path.exists():
                try:
                    temp_path.unlink()
                except Exception:
                    pass
            raise e


# ---------------------------------------------------------------------------
# Argumenten en configuratie inlezen
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).parent

# Windows-stijl /help en /? mappen naar --help voor argparse
for _i, _arg in enumerate(sys.argv):
    if _arg.lower() in ("/help", "/?", "?"):
        sys.argv[_i] = "--help"

parser = argparse.ArgumentParser(
    prog="html-album",
    description="Generates a static HTML photo album from a directory of JPEG images."
)
parser.add_argument(
    "config_file",
    nargs="?",
    default="html-album.rc",
    help="Path to the configuration file (default: %(default)s)"
)
parser.add_argument(
    "-V", "--version",
    action="version",
    version=f"%(prog)s {VERSION}",
    help="Show the program's version number and exit"
)
parser.add_argument(
    "-a", "--all",
    action="store_true",
    help="Force regeneration of all images and thumbnails"
)
parser.add_argument(
    "-r", "--reverse",
    action="store_true",
    help="Reversed order of folders and images (reverse)"
)
parser.add_argument(
    "--rename",
    action="store_true",
    help="Rename picture filenames to YYMMDD_HHMMSS-<orig-name> in output"
)
parser.add_argument(
    "-D", "--download",
    action="store_true",
    help="Show a download button on slide pages"
)
parser.add_argument(
    "-d", "--directory",
    metavar="DIR",
    help="Process only a specific (sub)directory"
)
parser.add_argument(
    "--no-exif", "--noexif", "--noEXIF", "--noEFIX",
    dest="no_exif",
    action="store_true",
    help="Disable EXIF metadata loading entirely"
)
parser.add_argument(
    "--rclone",
    nargs="*",
    metavar=("SRC", "DST"),
    help="Synchroniseer via 'rclone sync <SRC> <DST>' en verwerk aansluitend het album"
)

args = parser.parse_args()
config_naam = args.config_file
FORCE_ALL = args.all
CLI_REVERSE = args.reverse
CLI_RENAME = args.rename
CLI_DOWNLOAD = args.download
CLI_DIRECTORY = args.directory
CLI_NO_EXIF = args.no_exif
CLI_RCLONE = args.rclone


def _bepaal_config_pad(naam: str) -> Path:
    p = Path(naam)
    if p.is_absolute():
        return p
    if sys.platform != "win32":
        return Path.home() / "etc" / naam
    else:
        return SCRIPT_DIR / p

CONFIG_FILE = _bepaal_config_pad(config_naam)
if not CONFIG_FILE.exists() and not config_naam.lower().endswith(".rc"):
    config_naam_rc = f"{config_naam}.rc"
    cf_rc = _bepaal_config_pad(config_naam_rc)
    if cf_rc.exists():
        CONFIG_FILE = cf_rc
        config_naam = config_naam_rc


DEFAULTS = {
    "PICTURES_DIR": "_pictures",
    "THUMBS_DIR": "_thumbs",
    "EXCLUDED": ["res"],
    "THUMBNAIL": "140x140",
    "PICTURE": "",
    "SOURCE_DIR": "",
    "OUTPUT_DIR": "",
    "INDEX_FILE": "index.html",
    "LOG_FILE": "html-album.log",
    "COLUMNS": "0",
    "ROWS": "0",
    "FOOTER": _default_footer,
    "RENAME": "false",
    "DOWNLOAD": "no",
    "REVERSE": "no",
    "WATERMARK": "",
    "WM_FONT": "Verdana",
    "WM_SIZE": "12",
    "WM_ICON_SIZE": "0",
    "WM_TRANSPARANCY": "80%",
    "WM_LOCATION": "90",
    "WM_ALLIGNMENT": "center",
    "ICON": "Agrarix_Album_64x64.png",
    "NO_EXIF": "false",
    "RCLONE": "no",
    "RCLONE_SRC": "",
    "RCLONE_DST": "",
}


def _laad_config(pad: Path) -> dict:
    """Lees html-album.rc met KEY="VALUE" syntax."""
    config = {}
    try:
        with open(pad, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, val = line.split("=", 1)
                    key = key.strip()
                    val = val.strip()
                    if "#" in val:
                        parts = val.split("#", 1)
                        if parts[0].count('"') % 2 == 0 and parts[0].count("'") % 2 == 0:
                            val = parts[0].strip()
                    if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
                        val = val[1:-1]
                    if key == "EXCLUDED":
                        val = val.replace("[", "").replace("]", "").replace('"', '').replace("'", "")
                        config[key] = [x.strip() for x in val.split(",") if x.strip()]
                    else:
                        config[key] = val
        return config
    except Exception as e:
        print(f"ERROR loading {CONFIG_FILE.name}: {e}")
        sys.exit(1)

if CONFIG_FILE.exists():
    print(f"Configuratie geladen van: {CONFIG_FILE.resolve()}")
    cfg = {**DEFAULTS, **_laad_config(CONFIG_FILE)}
else:
    print(f"WARNING: Configuratiebestand {config_naam} niet gevonden.")
    time.sleep(1)
    default_config_file = _bepaal_config_pad("html-album.rc")
    if config_naam != "html-album.rc" and default_config_file.exists():
        print(f"Standaard configuratie geladen van: {default_config_file.resolve()}")
        cfg = {**DEFAULTS, **_laad_config(default_config_file)}
    else:
        cfg = DEFAULTS

RENAME_FILES = CLI_RENAME or cfg.get("RENAME", "false").lower() in ("true", "1", "yes")
DOWNLOAD_PICTURES = CLI_DOWNLOAD or cfg.get("DOWNLOAD", "no").lower() in ("true", "1", "yes")
REVERSE_ORDER = CLI_REVERSE or cfg.get("REVERSE", "no").lower() in ("true", "1", "yes")
DISABLE_EXIF = CLI_NO_EXIF or cfg.get("NO_EXIF", "false").lower() in ("true", "1", "yes")
DO_RCLONE = (CLI_RCLONE is not None) or cfg.get("RCLONE", "no").lower() in ("true", "1", "yes")


PICTURES_DIR_NAME: str = cfg.get("PICTURES_DIR", cfg.get("SLIDES_DIR", "_pictures"))
THUMBS_DIR_NAME: str = cfg["THUMBS_DIR"]
INDEX_FILE_NAME: str = cfg["INDEX_FILE"]
_raw_icon = cfg.get("ICON", "Agrarix_Album_64x64.png").strip().strip('"').strip("'")
ICON_FILE_NAME: str = Path(_raw_icon).name
SOURCE_DIR_RAW = os.path.expandvars(cfg.get("SOURCE_DIR", "")).strip()
OUTPUT_DIR_RAW = os.path.expandvars(cfg.get("OUTPUT_DIR", "")).strip()

if not SOURCE_DIR_RAW or SOURCE_DIR_RAW == ".":
    SOURCE_DIR = Path.cwd()
else:
    SOURCE_DIR = Path(SOURCE_DIR_RAW.replace("\\", "/")).resolve()

if not OUTPUT_DIR_RAW or OUTPUT_DIR_RAW == ".":
    OUTPUT_DIR = Path.cwd()
else:
    OUTPUT_DIR = Path(OUTPUT_DIR_RAW.replace("\\", "/")).resolve()

try:
    _w, _h = map(int, cfg["THUMBNAIL"].lower().split("x"))
    THUMB_SIZE = (_w, _h)
except ValueError:
    THUMB_SIZE = (140, 140)

PICTURE_SIZE = None
if cfg.get("PICTURE"):
    try:
        _wp, _hp = map(int, cfg["PICTURE"].lower().split("x"))
        PICTURE_SIZE = (_wp, _hp)
    except ValueError:
        pass

# Watermark configuratie
WATERMARK = cfg.get("WATERMARK", "").strip()
WM_FONT = cfg.get("WM_FONT", "Verdana").strip()

try:
    _wm_size_raw = cfg.get("WM_SIZE", "12").split("#")[0].strip()
    WM_SIZE = int(_wm_size_raw)
except ValueError:
    WM_SIZE = 12

try:
    _wm_icon_size_raw = cfg.get("WM_ICON_SIZE", "0").split("#")[0].strip()
    WM_ICON_SIZE = int(_wm_icon_size_raw)
except ValueError:
    WM_ICON_SIZE = 0

try:
    _wm_trans_raw = cfg.get("WM_TRANSPARANCY", "80%").split("#")[0].strip()
    if _wm_trans_raw.endswith("%"):
        WM_TRANSPARANCY = float(_wm_trans_raw[:-1]) / 100.0
    else:
        WM_TRANSPARANCY = float(_wm_trans_raw)
        if WM_TRANSPARANCY > 1.0:
            WM_TRANSPARANCY /= 100.0
except ValueError:
    WM_TRANSPARANCY = 0.80

try:
    _wm_loc_raw = cfg.get("WM_LOCATION", "90").split("#")[0].strip()
    WM_LOCATION = float(_wm_loc_raw)
except ValueError:
    WM_LOCATION = 90.0

WM_ALLIGNMENT = cfg.get("WM_ALLIGNMENT", cfg.get("WM_ALIGNMENT", "center")).split("#")[0].strip().lower()


EXCLUDED: set[str] = {
    x.lower() for x in (
        set(cfg["EXCLUDED"]) |
        {PICTURES_DIR_NAME, THUMBS_DIR_NAME, "pictures", "_pictures", "slides", "thumbs", "_thumbs", "slides_dir", "thumbs_dir", "pictures_dir"}
    )
}
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".heic", ".heif"}


KNOWN_ICON_NAMES = {
    "agrarix-pingu_2017.jpg",
    "new_pingu_agrarix_klompen.jpg",
    "agrarix_album_64x64.png",
    "agrarix_album.png",
    "agrarix_album.jpg",
}


def is_icon_file(path_or_name: Union[str, Path, None]) -> bool:
    """Controleert of een bestand of bestandsnaam het albumicoon is.
    
    Vergelijkt hoofdletterongevoelig en herkent ook bestanden die eventueel
    eerder per ongeluk zijn hernoemd met een datum-tijd prefix (YYMMDD_HHMMSS-).
    """
    if not path_or_name:
        return False
    name = Path(path_or_name).name.strip().lower()
    icon_name = Path(ICON_FILE_NAME).name.strip().lower() if ICON_FILE_NAME else ""
    target_names = ({icon_name} | KNOWN_ICON_NAMES) if icon_name else KNOWN_ICON_NAMES
    if name in target_names:
        return True
    stripped = re.sub(r"^\d{6}_\d{6}-", "", name)
    return stripped in target_names


def is_icon_stem(stem_or_name: Union[str, Path, None]) -> bool:
    """Controleert of een (afgeleide) bestandsnaam of stem bij een icoon hoort."""
    if not stem_or_name:
        return False
    stem = Path(stem_or_name).stem.strip().lower()
    target_names = ({ICON_FILE_NAME} if ICON_FILE_NAME else set()) | KNOWN_ICON_NAMES
    icon_stems = {Path(x).stem.lower() for x in target_names if x}
    clean_stem = re.sub(r"^\d{6}_\d{6}-", "", stem)
    clean_stem = re.sub(r"_thumb$", "", clean_stem)
    return clean_stem in icon_stems

# Bepaal het logbestand-pad. Als het een relatieve bestandsnaam is, zet het in SCRIPT_DIR (of $HOME/log op Linux).
cfg_log_file = os.path.expandvars(cfg.get("LOG_FILE", "html-album.log"))
if Path(cfg_log_file).is_absolute():
    LOG_FILE_PATH = Path(cfg_log_file.replace("\\", "/"))
elif sys.platform.startswith("linux"):
    LOG_FILE_PATH = Path.home() / "log" / cfg_log_file
else:
    LOG_FILE_PATH = SCRIPT_DIR / cfg_log_file

# Globale log-bestand handler
# (Wordt geïnitialiseerd in main)

def log_bericht(bericht: str) -> None:
    """Schrijft naar stdout én naar het logbestand html-album.log."""
    # Print direct naar het scherm (UTF-8)
    print(bericht)
    sys.stdout.flush()
    
    # Schrijf naar logbestand in de uitvoermap (indien geconfigureerd en beschikbaar)
    if LOG_FILE_PATH:
        try:
            with open(LOG_FILE_PATH, "a", encoding="utf-8") as lf:
                # Strip eventuele ansi-achtige tekens of print gewoon platte tekst
                schoon_bericht = bericht.replace("\U0001f4c2", "[DIR]").replace("\u2713", "[OK]").replace("\u2705", "[DONE]")
                lf.write(f"[{datetime.now().strftime('%H:%M:%S')}] {schoon_bericht}\n")
        except Exception:
            pass

def get_css() -> str:
    tw, th = THUMB_SIZE
    cell_w = tw + 10
    
    cols = int(cfg.get("COLUMNS", 0))
    if cols > 0:
        page_max_w = max(880, cell_w * cols + 40)
    else:
        page_max_w = max(880, cell_w * 2 + 40)
    
    css_path = SCRIPT_DIR / "html-album.css"
    if css_path.exists():
        css_res = css_path.read_text(encoding="utf-8")
    else:
        log_bericht("    ⚠ Warning: html-album.css not found in script directory! Minimal fallback styling will be used.")
        if sys.stdin.isatty():
            try:
                antwoord = input("    Press [Enter] to continue, or 'q' to stop: ").strip().lower()
                if antwoord == 'q':
                    log_bericht("    Generation aborted by user.")
                    sys.exit(0)
            except (EOFError, KeyboardInterrupt):
                pass
        css_res = "* { box-sizing: border-box; }"
    
    css_res = css_res.replace("max-width: 880px;", f"max-width: {page_max_w}px;")
    css_res = css_res.replace("width: 148px;", f"width: {cell_w}px;")
    css_res = css_res.replace("width: 138px;", f"width: {tw}px;")
    css_res = css_res.replace("height: 112px;", f"height: {th}px;")
    css_res = css_res.replace("max-width: 138px;", f"max-width: {tw}px;")
    css_res = css_res.replace("max-height: 112px;", f"max-height: {th}px;")
    css_res = css_res.replace("line-height: 112px;", f"line-height: {th}px;")
    
    if cols > 0:
        css_res += f"\n@media (max-width: 600px) {{\n    .thumb-grid {{\n        display: grid;\n        grid-template-columns: repeat({cols}, {cell_w}px);\n    }}\n}}\n"
    
    if th > 140:
        folder_font_size = min(120, int(th * 0.5))
        css_res = css_res.replace("font-size: 64px;", f"font-size: {folder_font_size}px;")
        
    return css_res

# ---------------------------------------------------------------------------
# Controleer of thumbnail opnieuw gegenereerd moet worden
# ---------------------------------------------------------------------------
def needs_thumbnail_regeneration(thumb_path: Path, src_path: Path) -> bool:
    if FORCE_ALL:
        return True
    if not thumb_path.exists():
        return True
    if not HAS_PIL:
        return False
    try:
        if src_path.stat().st_mtime > thumb_path.stat().st_mtime:
            return True
    except Exception:
        pass
    try:
        tw, th = THUMB_SIZE
        with Image.open(thumb_path) as img:
            # Als de thumbnail kleiner is dan de ingestelde THUMB_SIZE,
            # maar de bronfoto groter is dan de thumbnail, moet hij opnieuw
            with safe_image_open(src_path) as src_img:
                if (img.width < tw and img.height < th) and (src_img.width > img.width or src_img.height > img.height):
                    return True
            return not (img.width == tw or img.height == th or (img.width < tw and img.height < th))
    except Exception:
        return True

# ---------------------------------------------------------------------------
# Thumbnail maken met Pillow (bijgesneden vulling)
# ---------------------------------------------------------------------------
def make_thumbnail(src: Path, dst: Path) -> None:
    if not HAS_PIL:
        try:
            safe_copy(src, dst)
        except Exception as e:
            log_bericht(f"    ⚠  Could not copy file as thumbnail fallback: {e}")
        return
    try:
        with safe_image_open(src) as img:
            img = ImageOps.exif_transpose(img)
            img = img.convert("RGB")
            img.thumbnail(THUMB_SIZE, Image.LANCZOS)
            
            if WATERMARK and WM_ICON_SIZE > 0:
                img = apply_watermark(img, WM_ICON_SIZE)
                
            img.save(dst, "JPEG", quality=85, optimize=True)
    except PermissionError as pe:
        log_bericht(f"    ⚠  Access denied (file in use) while creating thumbnail for '{src.name}': {pe}")
    except Exception as exc:
        log_bericht(f"    ⚠  Thumbnail generation failed for '{src.name}': {exc}")
        try:
            safe_copy(src, dst)
        except Exception:
            pass

# ---------------------------------------------------------------------------
# Controleer of afbeelding opnieuw verkleind/gekopieerd moet worden
# ---------------------------------------------------------------------------
def needs_image_regeneration(dst_path: Path, src_path: Path) -> bool:
    if FORCE_ALL:
        return True
    if not dst_path.exists():
        return True
    try:
        if src_path.stat().st_mtime > dst_path.stat().st_mtime:
            return True
    except Exception:
        pass
    
    if HAS_PIL and PICTURE_SIZE:
        try:
            with Image.open(dst_path) as img:
                w, h = img.size
                pw, ph = PICTURE_SIZE
                if w > pw or h > ph:
                    return True
        except Exception:
            return True
    return False

# ---------------------------------------------------------------------------
# Grote afbeelding kopiëren/schalen met Pillow
# ---------------------------------------------------------------------------
def apply_watermark(img: "Image.Image", font_size: int) -> "Image.Image":
    """Voegt een semi-transparant watermerk toe aan de afbeelding met de opgegeven lettergrootte."""
    if not HAS_PIL or not WATERMARK or font_size <= 0:
        return img
        
    try:
        from PIL import ImageDraw, ImageFont
    except ImportError:
        return img

    try:
        # Maak een RGBA-laag voor het watermerk
        watermark_layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
        draw = ImageDraw.Draw(watermark_layer)
        
        # Probeer het geconfigureerde font te laden
        font = None
        font_paths = [
            WM_FONT,
            f"{WM_FONT}.ttf",
            f"{WM_FONT}.TTF",
        ]
        
        if sys.platform == "win32":
            font_paths.extend([
                f"C:\\Windows\\Fonts\\{WM_FONT}.ttf",
                f"C:\\Windows\\Fonts\\{WM_FONT}.TTF",
                f"C:\\Windows\\Fonts\\{WM_FONT}bd.ttf",
                "C:\\Windows\\Fonts\\arial.ttf",
            ])
        else:
            font_paths.extend([
                f"/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
                f"/usr/share/fonts/truetype/freefont/FreeSans.ttf",
                f"/usr/share/fonts/truetype/msttcorefonts/{WM_FONT}.ttf",
                f"/usr/share/fonts/truetype/msttcorefonts/{WM_FONT}.TTF",
            ])
            
        for path in font_paths:
            try:
                font = ImageFont.truetype(path, font_size)
                break
            except Exception:
                continue
                
        if font is None:
            font = ImageFont.load_default()
            
        # Bereken tekstafmetingen
        try:
            left, top, right, bottom = draw.textbbox((0, 0), WATERMARK, font=font)
            text_width = right - left
            text_height = bottom - top
        except AttributeError:
            text_width, text_height = draw.textsize(WATERMARK, font=font)
            
        # Bereken X op basis van uitlijning (left, center, right)
        if WM_ALLIGNMENT == "left":
            x = 20
        elif WM_ALLIGNMENT == "right":
            x = img.width - text_width - 20
        else:  # center
            x = (img.width - text_width) // 2
            
        y = int(img.height * WM_LOCATION / 100) - (text_height // 2)
        
        x = max(0, min(x, img.width - text_width))
        y = max(0, min(y, img.height - text_height))
        
        opacity = 1.0 - WM_TRANSPARANCY
        alpha = int(255 * max(0.0, min(1.0, opacity)))
        
        color = (255, 255, 255, alpha)
        draw.text((x, y), WATERMARK, font=font, fill=color)
        
        img_rgba = img.convert("RGBA")
        combined = Image.alpha_composite(img_rgba, watermark_layer)
        return combined.convert("RGB")
    except Exception as e:
        log_bericht(f"    ⚠  Fout bij toepassen watermerk: {e}")
        return img

def convert_heic_to_jpeg(src_path: Path, dst_path: Path) -> None:
    """Converteert een HEIC/HEIF afbeelding naar JPEG met behoud van EXIF-metadata."""
    if HAS_HEIF:
        with safe_image_open(src_path) as im:
            im = ImageOps.exif_transpose(im)
            exif_bytes = im.info.get("exif")
            if im.mode not in ("RGB", "L"):
                im = im.convert("RGB")
            if exif_bytes:
                im.save(dst_path, "JPEG", quality=95, optimize=True, exif=exif_bytes)
            else:
                im.save(dst_path, "JPEG", quality=95, optimize=True)
        return

    # Fallback via externe command-line tools indien beschikbaar
    for cmd in (
        ["heif-convert", str(src_path), str(dst_path)],
        ["convert", str(src_path), str(dst_path)],
        ["magick", str(src_path), str(dst_path)],
    ):
        try:
            res = subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            if res.returncode == 0 and dst_path.exists():
                return
        except Exception:
            continue

    raise RuntimeError("Geen HEIC converter beschikbaar (installeer 'pillow-heif': pip install pillow-heif)")

def make_resized_image(src: Path, dst: Path) -> None:
    if not HAS_PIL or not PICTURE_SIZE:
        try:
            safe_copy(src, dst)
        except Exception as e:
            log_bericht(f"    ⚠  Could not copy file: {e}")
        return
    try:
        with safe_image_open(src) as img:
            img = ImageOps.exif_transpose(img)
            img = img.convert("RGB")
            img.thumbnail(PICTURE_SIZE, Image.LANCZOS)
            
            if WATERMARK:
                img = apply_watermark(img, WM_SIZE)
                
            img.save(dst, "JPEG", quality=85, optimize=True)
    except PermissionError as pe:
        log_bericht(f"    ⚠  Access denied (file in use) while creating image for '{src.name}': {pe}")
    except Exception as exc:
        log_bericht(f"    ⚠  Resizing failed for '{src.name}': {exc}")
        try:
            safe_copy(src, dst)
        except Exception:
            pass

def get_exif_data(img_path: Path) -> dict:
    if DISABLE_EXIF or not HAS_PIL:
        return {}
    try:
        with safe_image_open(img_path) as img:
            exif = None
            if hasattr(img, "_getexif"):
                exif = img._getexif()
            if not exif and hasattr(img, "getexif"):
                exif = img.getexif()
            if not exif:
                return {}
            data = {}
            for tag, val in exif.items():
                tag_name = ExifTags.TAGS.get(tag, tag)
                data[tag_name] = val
            return data
    except Exception:
        return {}

def get_formatted_exif(img_path: Path) -> str:
    raw_exif = get_exif_data(img_path)
    if not raw_exif:
        return ""
    
    parts = []
    
    # Camera model
    make = raw_exif.get("Make", "")
    model = raw_exif.get("Model", "")
    if model:
        model_str = str(model).strip()
        make_str = str(make).strip()
        if make_str and make_str.lower() not in model_str.lower():
            parts.append(f"📷 {make_str} {model_str}")
        else:
            parts.append(f"📷 {model_str}")
            
    # Datum / Tijd
    dt_orig = raw_exif.get("DateTimeOriginal")
    if dt_orig:
        try:
            dt = datetime.strptime(str(dt_orig).strip(), "%Y:%m:%d %H:%M:%S")
            parts.append(f"📅 {dt.strftime('%d-%m-%Y %H:%M')}")
        except Exception:
            parts.append(f"📅 {str(dt_orig).strip()}")
            
    return "  •  ".join(parts)

def get_rename_prefix(img_path: Path) -> str:
    """Haalt de EXIF datum-tijd (of mtime) op en returnt YYMMDD_HHMMSS-."""
    exif = get_exif_data(img_path)
    dt_orig = exif.get("DateTimeOriginal")
    if dt_orig:
        try:
            dt = datetime.strptime(str(dt_orig).strip(), "%Y:%m:%d %H:%M:%S")
            return dt.strftime("%y%m%d_%H%M%S-")
        except Exception:
            pass
    try:
        mtime = img_path.stat().st_mtime
        dt = datetime.fromtimestamp(mtime)
        return dt.strftime("%y%m%d_%H%M%S-")
    except Exception:
        return ""

def get_new_filename(img_path: Path) -> str:
    orig_name = img_path.name
    if is_icon_file(orig_name):
        return Path(ICON_FILE_NAME).name
    is_heic = img_path.suffix.lower() in (".heic", ".heif")
    base_name = f"{img_path.stem}.jpg" if is_heic else orig_name
    if not RENAME_FILES:
        return base_name
    if re.match(r"^\d{6}_\d{6}-", orig_name):
        return f"{img_path.stem}.jpg" if is_heic else orig_name
    prefix = get_rename_prefix(img_path)
    return f"{prefix}{base_name}"

# ---------------------------------------------------------------------------
# Genereer HTML voor één slide-pagina
# ---------------------------------------------------------------------------
def generate_slide_html(
    out_file: Path,
    img_fname: str,
    prev_slide: str,
    next_slide: str,
    index_href: str,
    slide_breadcrumb_html: str,
    src_img_path: Path,
    css_href: str,
) -> None:
    prev_js = f'"{prev_slide}"' if prev_slide else "null"
    next_js = f'"{next_slide}"' if next_slide else "null"
    dl_js = f'"{img_fname}"' if DOWNLOAD_PICTURES else "null"

    svg_left = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" style="display: inline-block; vertical-align: middle;"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>'
    svg_right = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" style="display: inline-block; vertical-align: middle;"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>'

    prev_btn = f'<span class="nav-btn prev-btn disabled" title="No previous picture">{svg_left}</span>'
    next_btn = f'<span class="nav-btn next-btn disabled" title="No next picture">{svg_right}</span>'
    if prev_slide:
        prev_btn = f'<a href="{prev_slide}" class="nav-btn prev-btn" title="Previous picture (&#8592;)">{svg_left}</a>'
    if next_slide:
        next_btn = f'<a href="{next_slide}" class="nav-btn next-btn" title="Next picture (&#8594;)">{svg_right}</a>'

    if DOWNLOAD_PICTURES:
        svg_download = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" style="display: inline-block; vertical-align: middle;"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>'
        dl_btn = f'<a href="../{img_fname}" download="{img_fname}" class="nav-btn dl-btn" title="Download picture">{svg_download}</a>'
    else:
        dl_btn = ""

    exif_str = get_formatted_exif(src_img_path)
    exif_html = f'<div class="slide-exif">{exif_str}</div>' if exif_str else ""

    img_src = img_fname if PICTURE_SIZE else f"../{img_fname}"

    svg_up = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" style="display: inline-block; vertical-align: middle;"><line x1="12" y1="19" x2="12" y2="5"></line><polyline points="5 12 12 5 19 12"></polyline></svg>'

    out_dir = out_file.parent.parent
    rel_parts = [p for p in out_dir.relative_to(OUTPUT_DIR).parts if p not in ('.', '/')]
    relative_path_to_root = "../" * len(rel_parts)
    favicon_tag = ""
    pingu_icon_path = OUTPUT_DIR / ICON_FILE_NAME
    if pingu_icon_path.exists():
        favicon_tag = f'\n    <link rel="icon" href="../{relative_path_to_root}{ICON_FILE_NAME}">'

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">{favicon_tag}
    <title>{img_fname}</title>
    <link rel="stylesheet" href="{css_href}">
</head>
<body>
<div class="page-wrap">
    <div class="album-header">
        <a href="{index_href}" class="nav-btn up-btn" title="Back to album (↑)">{svg_up}</a>
        <span class="header-title">{slide_breadcrumb_html}</span>
        <div class="header-nav">
            {dl_btn}
            {prev_btn}
            {next_btn}
        </div>
    </div>
    <div class="slide-wrap">
        <img src="{img_src}" alt="{img_fname}" class="slide-image">
        <div class="slide-info">{img_fname}</div>
        {exif_html}
    </div>
</div>
<script>
var prevSlide = {prev_js};
var nextSlide = {next_js};
var dlFilename = {dl_js};
document.addEventListener('keydown', function(e) {{
    switch (e.key) {{
        case 'ArrowLeft':
            if (prevSlide) window.location = prevSlide; break;
        case 'ArrowRight': case ' ':
            if (nextSlide) window.location = nextSlide; break;
        case 'Backspace':  case 'Escape':
            window.location = '{index_href}'; break;
    }}
}});

var slideImg = document.querySelector('.slide-image');
if (slideImg) {{
    slideImg.addEventListener('mousemove', function(e) {{
        var rect = this.getBoundingClientRect();
        var x = e.clientX - rect.left;
        var y = e.clientY - rect.top;
        var w = rect.width;
        var h = rect.height;
        if (x < w / 3) {{
            if (prevSlide) {{
                this.style.cursor = 'w-resize';
                this.title = 'Previous picture (←)';
            }} else {{
                this.style.cursor = 'default';
                this.title = '';
            }}
        }} else if (x > (2 * w) / 3) {{
            if (nextSlide) {{
                this.style.cursor = 'e-resize';
                this.title = 'Next picture (→)';
            }} else {{
                this.style.cursor = 'default';
                this.title = '';
            }}
        }} else if (y < h * 0.3) {{
            this.style.cursor = 'n-resize';
            this.title = 'Back to album (↑)';
        }} else if (dlFilename) {{
            this.style.cursor = 's-resize';
            this.title = 'Download picture (↓)';
        }} else {{
            this.style.cursor = 'default';
            this.title = '';
        }}
    }});
    slideImg.addEventListener('click', function(e) {{
        var rect = this.getBoundingClientRect();
        var x = e.clientX - rect.left;
        var y = e.clientY - rect.top;
        var w = rect.width;
        var h = rect.height;
        if (x < w / 3) {{
            if (prevSlide) window.location = prevSlide;
        }} else if (x > (2 * w) / 3) {{
            if (nextSlide) window.location = nextSlide;
        }} else if (y < h * 0.3) {{
            window.location = '{index_href}';
        }} else if (dlFilename) {{
            var link = document.createElement('a');
            link.href = '../' + dlFilename;
            link.download = dlFilename;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        }}
    }});
}}
</script>
</body>
</html>
"""
    out_file.write_text(html, encoding="utf-8")

# ---------------------------------------------------------------------------
# Genereer index.html voor één map
# ---------------------------------------------------------------------------
def generate_index_html(
    index_file: Path,
    title: str,
    breadcrumb_html: str,
    up_href: str,
    src_dir: Path,
    out_dir: Path,
    css_href: str,
) -> None:
    generated_date = datetime.now().strftime("%d-%m-%Y %H:%M")

    up_btn = ""
    if up_href:
        svg_up = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" style="display: inline-block; vertical-align: middle;"><line x1="12" y1="19" x2="12" y2="5"></line><polyline points="5 12 12 5 19 12"></polyline></svg>'
        up_btn = f'<a href="{up_href}" class="nav-btn up-btn" title="Up to parent directory">{svg_up}</a>'

    images = sorted(
        [f for f in src_dir.iterdir() if f.is_file() and f.suffix.lower() in IMAGE_EXTS and not is_icon_file(f)],
        key=lambda f: f.name.lower(),
        reverse=REVERSE_ORDER,
    )

    img_cells: list[str] = []
    for i, img in enumerate(images):
        fname       = get_new_filename(img)
        name_no_ext = Path(fname).stem
        thumb_rel   = f"{THUMBS_DIR_NAME}/{name_no_ext}_thumb.jpg"
        slide_rel   = f"{PICTURES_DIR_NAME}/{name_no_ext}.html"
        
        cell_class = "thumb-cell"
        title_text = fname
        label_text = fname
        
        img_cells.append(
            f'        <div class="{cell_class}">\n'
            f'            <a href="{slide_rel}" title="{title_text}">\n'
            f'                <div class="thumb-img-wrap">\n'
            f'                    <img src="{thumb_rel}" alt="{fname}" loading="lazy">\n'
            f'                </div>\n'
            f'                <div class="thumb-label">{label_text}</div>\n'
            f'            </a>\n'
            f'        </div>'
        )

    subdirs = sorted(
        [d for d in src_dir.iterdir() if d.is_dir() and d.name.lower() not in EXCLUDED],
        key=lambda d: d.name.lower(),
        reverse=REVERSE_ORDER,
    )

    dir_cells: list[str] = []
    for subdir in subdirs:
        dname            = subdir.name

        first_img = next(
            (f for f in sorted(subdir.iterdir(), key=lambda x: x.name.lower(), reverse=REVERSE_ORDER) if f.is_file() and f.suffix.lower() in IMAGE_EXTS and not is_icon_file(f)),
            None,
        )

        rel_parts = [p for p in out_dir.relative_to(OUTPUT_DIR).parts if p not in ('.', '/')]
        relative_path_to_root = "../" * len(rel_parts)

        if first_img:
            first_img_stem = Path(get_new_filename(first_img)).stem
            folder_thumb_dst = out_dir / THUMBS_DIR_NAME / f"folder_{dname}_{first_img_stem}_thumb.jpg"
            if needs_thumbnail_regeneration(folder_thumb_dst, first_img):
                make_thumbnail(first_img, folder_thumb_dst)
                log_bericht(f"    ✓ Folder '{dname}' ({THUMBS_DIR_NAME}/ with photo: {first_img.name})")
            else:
                log_bericht(f"    ✓ Folder '{dname}' (unchanged, photo: {first_img.name})")
            thumb_tag = f'<img src="{THUMBS_DIR_NAME}/folder_{dname}_{first_img_stem}_thumb.jpg" alt="{dname}" loading="lazy">'
            label = f"\U0001f4c1 {dname}"
        else:
            pingu_icon_path = OUTPUT_DIR / ICON_FILE_NAME
            if pingu_icon_path.exists():
                thumb_tag = f'<img src="{relative_path_to_root}{ICON_FILE_NAME}" alt="{dname}" loading="lazy">'
                label     = f"\U0001f4c1 {dname}"
            else:
                thumb_tag = '<div class="folder-icon">\U0001f4c1</div>'
                label     = dname

        dir_cells.append(
            f'        <div class="thumb-cell folder">\n'
            f'            <a href="{dname}/{INDEX_FILE_NAME}" title="{dname}">\n'
            f'                <div class="thumb-img-wrap">\n'
            f'                    {thumb_tag}\n'
            f'                </div>\n'
            f'                <div class="thumb-label">{label}</div>\n'
            f'            </a>\n'
            f'        </div>'
        )

    all_cells = "\n".join(img_cells + dir_cells)

    # Formateer datum en tijd
    now = datetime.now()
    date_str = now.strftime("%d-%m-%Y")
    time_str = now.strftime("%H:%M")

    # === START FOOTER VERVANGING ===
    footer_tmpl = cfg.get("FOOTER", _default_footer)
    footer_text = footer_tmpl
    pgm_link = f'<a href="https://github.com/agrarix/{PGM}">{PGM}</a>'
    footer_text = footer_text.replace("${PGM}", pgm_link).replace("{PGM}", pgm_link)
    footer_text = footer_text.replace("v${VER}", "${VER}").replace("v{VER}", "{VER}").replace("v${VERSION}", "${VERSION}").replace("v{VERSION}", "{VERSION}")
    footer_text = footer_text.replace("${VER}", VERSION).replace("{VER}", VERSION).replace("{VERSION}", VERSION)
    footer_text = footer_text.replace("${DATE}", date_str).replace("{date_str}", date_str)
    footer_text = footer_text.replace("${TIME}", time_str).replace("{time_str}", time_str)
    if sys.platform != "win32":
        footer_text = footer_text.replace("(${OS})", f"(Linux) at {_hostname}").replace("({OS})", f"(Linux) at {_hostname}")
        if f"(Linux) at" not in footer_text:
            footer_text = footer_text.replace("(Linux)", f"(Linux) at {_hostname}")
    footer_text = footer_text.replace("${OS}", _os_naam).replace("{OS}", _os_naam)
    footer_text = footer_text.replace("${HOSTNAME}", _hostname).replace("{HOSTNAME}", _hostname)
    # === END FOOTER VERVANGING ===

    up_script = ""
    if up_href:
        up_script = f"""<script>
document.addEventListener('keydown', function(e) {{
    if (e.key === 'Backspace' || e.key === 'Escape') {{
        window.location = '{up_href}';
    }}
}});
</script>
"""

    rel_parts = [p for p in out_dir.relative_to(OUTPUT_DIR).parts if p not in ('.', '/')]
    relative_path_to_root = "../" * len(rel_parts)
    favicon_tag = ""
    pingu_icon_path = OUTPUT_DIR / ICON_FILE_NAME
    if pingu_icon_path.exists():
        favicon_tag = f'\n    <link rel="icon" href="{relative_path_to_root}{ICON_FILE_NAME}">'

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="photoalbum,gallery,photo,online">{favicon_tag}
    <title>{title}</title>
    <link rel="stylesheet" href="{css_href}">
</head>
<body>
<div class="page-wrap">
    <div class="album-header">
        {up_btn}
        <span class="header-title">{breadcrumb_html}</span>
    </div>
    <div class="thumb-grid">
{all_cells}
    </div>
    <center>
    <div class="footer">{footer_text}</div>
    </center>
</div>
{up_script}</body>
</html>
"""
    try:
        index_file.write_text(html, encoding="utf-8")
    except PermissionError as pe:
        log_bericht(f"\n❌ Error: Kon {index_file.name} niet schrijven (ReadOnly of geen toegang): {pe}")
        sys.exit(1)

# ---------------------------------------------------------------------------
# Recursieve mapverwerking
# ---------------------------------------------------------------------------
def process_dir(
    src_dir: Path,
    out_dir: Path,
    parent_index: str,
    title: str,
) -> None:
    log_bericht(f"\U0001f4c2  {title}")
    log_bericht(f"    source : {src_dir}")
    log_bericht(f"    output : {out_dir}")

    out_dir.mkdir(parents=True, exist_ok=True)
    pics_dir = out_dir / PICTURES_DIR_NAME
    if pics_dir.exists() and not pics_dir.is_dir():
        pics_dir.unlink()
    pics_dir.mkdir(exist_ok=True)

    thumbs_dir = out_dir / THUMBS_DIR_NAME
    if thumbs_dir.exists() and not thumbs_dir.is_dir():
        thumbs_dir.unlink()
    thumbs_dir.mkdir(exist_ok=True)

    # Herstel eventueel per ongeluk hernoemd icoonbestand in src_dir terug naar originele ICON_FILE_NAME
    target_icon_name = Path(ICON_FILE_NAME).name
    for f in list(src_dir.iterdir()):
        if f.is_file() and is_icon_file(f) and f.name.lower() != target_icon_name.lower():
            target_file = src_dir / target_icon_name
            if not target_file.exists():
                try:
                    try:
                        os.chmod(f, 0o666)
                    except Exception:
                        pass
                    try:
                        f.rename(target_file)
                    except Exception:
                        shutil.move(str(f), str(target_file))
                    log_bericht(f"    ✓ Icoon hersteld: '{f.name}' -> '{target_icon_name}'")
                except Exception as exc:
                    log_bericht(f"    ⚠ Kon hernoemd icoon niet herstellen: {exc}")
            else:
                try:
                    try:
                        os.chmod(f, 0o666)
                    except Exception:
                        pass
                    f.unlink()
                    log_bericht(f"    🧹 Dubbel hernoemd icoon verwijderd: '{f.name}'")
                except Exception:
                    pass

    # Verwijder eventuele oude gegenereerde slide/thumb van het icoon als die nog aanwezig zijn
    for old_slide in pics_dir.glob("*"):
        if is_icon_stem(old_slide.name):
            try:
                old_slide.unlink()
                log_bericht(f"    🧹 Oude slide van icoon verwijderd: {old_slide.name}")
            except Exception:
                pass
    for old_thumb in thumbs_dir.glob("*"):
        if is_icon_stem(old_thumb.name):
            try:
                old_thumb.unlink()
                log_bericht(f"    🧹 Oude thumbnail van icoon verwijderd: {old_thumb.name}")
            except Exception:
                pass

    images = sorted(
        [f for f in src_dir.iterdir() if f.is_file() and f.suffix.lower() in IMAGE_EXTS and not is_icon_file(f)],
        key=lambda f: f.name.lower(),
        reverse=REVERSE_ORDER,
    )
    log_bericht(f"    photos : {len(images)}")

    # Bereken relatieve pad naar OUTPUT_DIR root voor CSS link
    rel_parts = [p for p in out_dir.relative_to(OUTPUT_DIR).parts if p not in ('.', '/')]
    relative_path_to_root = "../" * len(rel_parts)
    
    version_str = datetime.now().strftime("%Y%m%d%H%M%S")
    index_css_href = f"{relative_path_to_root}html-album.css?v={version_str}"
    slide_css_href = f"../{relative_path_to_root}html-album.css?v={version_str}"

    # Bouw kruimelpad (breadcrumbs)
    rel_path = src_dir.relative_to(SOURCE_DIR)
    root_name = SOURCE_DIR.name
    root_display = f"Photo album : {root_name}"
    
    if rel_path == Path('.'):
        breadcrumb_html = f'<a href="{INDEX_FILE_NAME}">{root_display}</a>'
        slide_breadcrumb_html = f'<a href="../{INDEX_FILE_NAME}">{root_display}</a>'
    else:
        links = []
        slide_links = []
        depth = len(rel_path.parts)
        slide_depth = depth + 1
        
        # Voor indexpagina's
        links.append(f'<a href="{"../" * depth}{INDEX_FILE_NAME}">{root_name}</a>')
        for idx, part_name in enumerate(rel_path.parts[:-1]):
            steps_up = depth - 1 - idx
            links.append(f'<a href="{"../" * steps_up}{INDEX_FILE_NAME}">{part_name}</a>')
        links.append(f'<a href="{INDEX_FILE_NAME}">{rel_path.parts[-1]}</a>')
        breadcrumb_html = " / ".join(links)
        
        # Voor slidepagina's (één niveau dieper wegens slides/ submap)
        slide_links.append(f'<a href="{"../" * slide_depth}{INDEX_FILE_NAME}">{root_name}</a>')
        for idx, part_name in enumerate(rel_path.parts[:-1]):
            steps_up = slide_depth - 1 - idx
            slide_links.append(f'<a href="{"../" * steps_up}{INDEX_FILE_NAME}">{part_name}</a>')
        slide_links.append(f'<a href="../{INDEX_FILE_NAME}">{rel_path.parts[-1]}</a>')
        slide_breadcrumb_html = " / ".join(slide_links)

    # Bepaal target bestandsnamen voor alle afbeeldingen in deze directory
    mapped_images = []
    for img in images:
        target_name = get_new_filename(img)
        target_stem = Path(target_name).stem
        mapped_images.append((img, target_name, target_stem))

    for i, (img, fname, name_no_ext) in enumerate(mapped_images):
        actions     = []

        # Kopieer of hernoem het origineel naar de uitvoermap (en converteer HEIC/HEIF naar JPEG)
        is_heic = img.suffix.lower() in (".heic", ".heif")
        dst_img = out_dir / fname
        if dst_img != img or is_heic:
            if is_heic:
                if not dst_img.exists() or FORCE_ALL:
                    try:
                        convert_heic_to_jpeg(img, dst_img)
                        actions.append("heic->jpg")
                        if img.parent == dst_img.parent and img.exists() and img != dst_img:
                            try:
                                img.unlink()
                            except Exception:
                                pass
                        img = dst_img
                    except Exception as e:
                        log_bericht(f"    ⚠  Fout bij converteren HEIC '{img.name}' naar '{fname}': {e}")
                else:
                    img = dst_img
            elif img.parent == dst_img.parent:
                # Bron- en doelmap zijn hetzelfde: fysiek hernoemen
                if not dst_img.exists():
                    try:
                        img.rename(dst_img)
                        img = dst_img  # Update img naar het nieuwe pad voor thumbnails/exif
                        actions.append("renamed")
                    except Exception as e:
                        log_bericht(f"    ⚠  Error renaming '{img.name}' to '{fname}': {e}")
                else:
                    # Als de hernoemde versie al bestaat, update het pad naar het bestaande bestand
                    img = dst_img
            else:
                # Bron- en doelmap zijn verschillend: kopiëren
                if not dst_img.exists():
                    try:
                        safe_copy(img, dst_img)
                        actions.append("./")
                    except PermissionError as pe:
                        log_bericht(f"    ⚠  Permission denied copying '{fname}': {pe}")
                    except Exception as e:
                        log_bericht(f"    ⚠  Error copying '{fname}': {e}")

        # Genereer verkleinde versie in pictures/ indien PICTURE_SIZE is ingesteld
        if PICTURE_SIZE:
            dst_resized = out_dir / PICTURES_DIR_NAME / fname
            if needs_image_regeneration(dst_resized, img):
                make_resized_image(img, dst_resized)
                actions.append(f"{PICTURES_DIR_NAME}/")

        thumb = out_dir / THUMBS_DIR_NAME / f"{name_no_ext}_thumb.jpg"
        if needs_thumbnail_regeneration(thumb, img):
            make_thumbnail(img, thumb)
            actions.append(f"{THUMBS_DIR_NAME}/")

        prev_slide = mapped_images[i - 1][2] + ".html" if i > 0 else ""
        next_slide = mapped_images[i + 1][2] + ".html" if i < len(mapped_images) - 1 else ""

        generate_slide_html(
            out_dir / PICTURES_DIR_NAME / f"{name_no_ext}.html",
            fname,
            prev_slide,
            next_slide,
            f"../{INDEX_FILE_NAME}",
            f"{slide_breadcrumb_html} ({i + 1}/{len(mapped_images)})",
            img,
            slide_css_href,
        )
        
        if actions:
            log_bericht(f"    ✓ {fname} ({', '.join(actions)})")
        else:
            log_bericht(f"    ✓ {fname} (unchanged)")

    generate_index_html(
        out_dir / INDEX_FILE_NAME,
        title,
        breadcrumb_html,
        parent_index,
        src_dir,
        out_dir,
        index_css_href,
    )

    subdirs = sorted(
        [d for d in src_dir.iterdir() if d.is_dir() and d.name.lower() not in EXCLUDED],
        key=lambda d: d.name.lower(),
        reverse=REVERSE_ORDER,
    )
    for subdir in subdirs:
        process_dir(
            subdir,
            out_dir / subdir.name,
            f"../{INDEX_FILE_NAME}",
            subdir.name,
        )

# ---------------------------------------------------------------------------
# Startpunt
# ---------------------------------------------------------------------------
def main() -> None:
    global LOG_FILE_PATH, SOURCE_DIR, CLI_DIRECTORY
    
    if LOG_FILE_PATH:
        LOG_FILE_PATH.parent.mkdir(parents=True, exist_ok=True)
        try:
            with open(LOG_FILE_PATH, "w", encoding="utf-8") as lf:
                lf.write(f"=== Album Generator Log {datetime.now().strftime('%d-%m-%Y %H:%M:%S')} ===\n")
        except Exception as exc:
            print(f"Kon logbestand niet maken op {LOG_FILE_PATH}: {exc}")

    rclone_src = ""
    rclone_dst = ""
    if DO_RCLONE:
        if CLI_RCLONE and len(CLI_RCLONE) == 2:
            rclone_src = CLI_RCLONE[0].strip()
            rclone_dst = CLI_RCLONE[1].strip()
        elif CLI_RCLONE and len(CLI_RCLONE) not in (0, 2):
            log_bericht("\n❌ Error: --rclone vereist 2 argumenten: BRON en DOEL (of 0 indien geconfigureerd in .rc).")
            sys.exit(1)
        else:
            rclone_src = cfg.get("RCLONE_SRC", "").strip()
            rclone_dst = cfg.get("RCLONE_DST", "").strip()

        if not rclone_src or not rclone_dst:
            log_bericht("\n❌ Error: RCLONE is geactiveerd, maar RCLONE_SRC en/of RCLONE_DST ontbreken.")
            log_bericht("   Geef argumenten mee via --rclone <BRON> <DOEL> of stel in via html-album.rc.")
            sys.exit(1)

        src_clean = rclone_src.rstrip("/\\")
        dst_clean = rclone_dst.rstrip("/\\")
        src_name = Path(src_clean).name
        dst_name = Path(dst_clean).name

        if not src_name or not dst_name or src_name != dst_name:
            log_bericht(f"\n❌ Fout: Laatste sub-mappen van bron en doel moeten exact gelijk zijn:")
            log_bericht(f"   Bron sub-map : '{src_name}' ({rclone_src})")
            log_bericht(f"   Doel sub-map : '{dst_name}' ({rclone_dst})")
            log_bericht("   Synchronisatie en albumgeneratie afgebroken.")
            sys.exit(1)

        log_bericht("═" * 50)
        log_bericht("🚀 Start rclone sync:")
        log_bericht(f"   Bron : {rclone_src}")
        log_bericht(f"   Doel : {rclone_dst}")
        log_bericht("═" * 50)
        try:
            cmd = [
                "rclone", "sync", rclone_src, rclone_dst,
                "-v",
                "--create-empty-src-dirs",
                "--exclude", f"**/{PICTURES_DIR_NAME}/**",
                "--exclude", f"**/{THUMBS_DIR_NAME}/**",
                "--exclude", "**/html-album.css",
                "--exclude", f"**/{INDEX_FILE_NAME}",
                "--exclude", "**/*.log",
            ]
            proc = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                bufsize=1,
                universal_newlines=True,
                encoding="utf-8",
                errors="replace",
            )
            if proc.stdout:
                for raw_line in proc.stdout:
                    line = raw_line.strip()
                    if line:
                        log_bericht(f"   [rclone] {line}")
            ret = proc.wait()
            if ret != 0:
                log_bericht(f"\n❌ Fout: rclone sync mislukt (exit code {ret})")
                log_bericht("   Albumgeneratie afgebroken.")
                sys.exit(ret)
        except FileNotFoundError:
            log_bericht("\n❌ Fout: 'rclone' commando niet gevonden. Controleer installatie en PATH.")
            log_bericht("   Albumgeneratie afgebroken.")
            sys.exit(1)
        except Exception as exc:
            log_bericht(f"\n❌ Fout tijdens rclone sync: {exc}")
            log_bericht("   Albumgeneratie afgebroken.")
            sys.exit(1)

        log_bericht("✓ rclone sync succesvol voltooid.\n")

        dst_path = Path(dst_clean).resolve()

        # Controleer en verwijder vervallen mappen in het doel die niet (meer) in de bron bestaan
        if dst_path.exists():
            try:
                lsf_cmd = ["rclone", "lsf", "--dirs-only", "-R", rclone_src]
                lsf_res = subprocess.run(
                    lsf_cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    encoding="utf-8",
                    errors="replace",
                )
                if lsf_res.returncode == 0:
                    src_dirs = {
                        line.strip().rstrip("/\\").replace("\\", "/")
                        for line in lsf_res.stdout.splitlines()
                        if line.strip()
                    }
                    # Zoek alle submappen in dst_path gesorteerd op diepte (diepste eerst)
                    for item in sorted(dst_path.rglob("*"), key=lambda p: len(p.parts), reverse=True):
                        if not item.exists() or not item.is_dir():
                            continue
                        if item.name.startswith(".") or item.name.lower() in EXCLUDED:
                            continue
                        if item.name == PICTURES_DIR_NAME or item.name == THUMBS_DIR_NAME:
                            continue
                        if any(part in (PICTURES_DIR_NAME, THUMBS_DIR_NAME) for part in item.parts):
                            continue
                        try:
                            rel = item.relative_to(dst_path)
                            rel_str = str(rel).replace("\\", "/").rstrip("/")
                        except ValueError:
                            continue

                        if rel_str and rel_str not in src_dirs:
                            try:
                                # Verwijder ook bijbehorende preview-thumbnail van deze map in bovenliggende _thumbs
                                for ft in (item.parent / THUMBS_DIR_NAME).glob(f"folder_{item.name}_*"):
                                    try:
                                        ft.unlink()
                                    except Exception:
                                        pass
                                shutil.rmtree(item)
                                log_bericht(f"   🧹 Vervallen map verwijderd (niet in bron): {rel_str}")
                            except Exception as rm_err:
                                log_bericht(f"   ⚠ Kon vervallen map niet verwijderen ({rel_str}): {rm_err}")
            except Exception as lsf_err:
                log_bericht(f"   ⚠ Kon bronmappen niet verifiëren via rclone lsf: {lsf_err}")
        if SOURCE_DIR.resolve() == dst_path:
            # SOURCE_DIR is al exact de doelmap zelf, geen submap filter nodig
            pass
        else:
            try:
                dst_rel = dst_path.relative_to(SOURCE_DIR)
                if not CLI_DIRECTORY:
                    CLI_DIRECTORY = str(dst_rel)
            except ValueError:
                SOURCE_DIR = dst_path.parent
                if not CLI_DIRECTORY:
                    CLI_DIRECTORY = dst_name

    if not SOURCE_DIR or not SOURCE_DIR.exists():
        print(f"\n❌ Source directory not found: {SOURCE_DIR}")
        print("   Adjust SOURCE_DIR in html-album.rc")
        sys.exit(1)

    if not OUTPUT_DIR:
        print("\n❌ OUTPUT_DIR is not set")
        sys.exit(1)
        
    # Maak output directory aan indien nodig
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Formateer footer preview
    now = datetime.now()
    date_str = now.strftime("%d-%m-%Y")
    time_str = now.strftime("%H:%M")
    footer_tmpl = cfg.get("FOOTER", _default_footer)
    footer_preview = footer_tmpl
    pgm_link = f'<a href="https://github.com/agrarix/{PGM}">{PGM}</a>'
    footer_preview = footer_preview.replace("${PGM}", pgm_link).replace("{PGM}", pgm_link)
    footer_preview = footer_preview.replace("v${VER}", "${VER}").replace("v{VER}", "{VER}").replace("v${VERSION}", "${VERSION}").replace("v{VERSION}", "{VERSION}")
    footer_preview = footer_preview.replace("${VER}", VERSION).replace("{VER}", VERSION).replace("{VERSION}", VERSION)
    footer_preview = footer_preview.replace("${DATE}", date_str).replace("{date_str}", date_str)
    footer_preview = footer_preview.replace("${TIME}", time_str).replace("{time_str}", time_str)
    if sys.platform != "win32":
        footer_preview = footer_preview.replace("(${OS})", f"(Linux) at {_hostname}").replace("({OS})", f"(Linux) at {_hostname}")
        if f"(Linux) at" not in footer_preview:
            footer_preview = footer_preview.replace("(Linux)", f"(Linux) at {_hostname}")
    footer_preview = footer_preview.replace("${OS}", _os_naam).replace("{OS}", _os_naam)
    footer_preview = footer_preview.replace("${HOSTNAME}", _hostname).replace("{HOSTNAME}", _hostname)

    target_src_dir = SOURCE_DIR
    target_out_dir = OUTPUT_DIR
    parent_index = ""
    root_title = SOURCE_DIR.name
    rel_path = Path('.')

    if CLI_DIRECTORY:
        dir_path = Path(CLI_DIRECTORY)
        if dir_path.is_absolute():
            candidate = dir_path.resolve()
        else:
            candidate = (SOURCE_DIR / dir_path).resolve()
            if not candidate.exists():
                matching = [d for d in SOURCE_DIR.rglob("*") if d.is_dir() and d.name.lower() == CLI_DIRECTORY.lower()]
                if matching:
                    candidate = matching[0].resolve()

        if not candidate.exists() or not candidate.is_dir():
            log_bericht(f"❌ Directory not found: {CLI_DIRECTORY}")
            sys.exit(1)

        target_src_dir = candidate
        try:
            rel_path = target_src_dir.relative_to(SOURCE_DIR)
        except ValueError:
            rel_path = Path('.')

        if rel_path == Path('.'):
            target_out_dir = OUTPUT_DIR
            parent_index = ""
            root_title = target_src_dir.name
        else:
            target_out_dir = OUTPUT_DIR / rel_path
            parent_index = "../" * len(rel_path.parts) + INDEX_FILE_NAME
            root_title = target_src_dir.name

    # Controleer bij de start of INDEX_FILE herschrijfbaar is (niet ReadOnly)
    target_index_file = target_out_dir / INDEX_FILE_NAME
    if not is_file_writable(target_index_file):
        log_bericht(f"\n❌ Error: INDEX_FILE '{INDEX_FILE_NAME}' is ReadOnly of niet herschrijfbaar: {target_index_file}")
        log_bericht("   Generatie afgebroken.")
        sys.exit(1)

    if target_out_dir != OUTPUT_DIR:
        root_index_file = OUTPUT_DIR / INDEX_FILE_NAME
        if root_index_file.exists() and not is_file_writable(root_index_file):
            log_bericht(f"\n❌ Error: INDEX_FILE '{INDEX_FILE_NAME}' is ReadOnly of niet herschrijfbaar: {root_index_file}")
            log_bericht("   Generatie afgebroken.")
            sys.exit(1)

    log_bericht("HTML Photo Album Generator")
    log_bericht("─" * 36)
    log_bericht(f"CONFIG_FILE   : {CONFIG_FILE} (Path: {CONFIG_FILE.resolve()})")
    log_bericht(f"SOURCE_DIR    : {SOURCE_DIR}")
    log_bericht(f"OUTPUT_DIR    : {OUTPUT_DIR}")
    if CLI_DIRECTORY:
        log_bericht(f"TARGET_DIR    : {target_src_dir} (relative: {rel_path})")
    log_bericht(f"LOG_FILE      : {cfg.get('LOG_FILE')} (Path: {LOG_FILE_PATH})")
    log_bericht(f"INDEX_FILE    : {INDEX_FILE_NAME}")
    log_bericht(f"ICON          : {ICON_FILE_NAME}")
    log_bericht(f"PICTURES_DIR  : {PICTURES_DIR_NAME}")
    log_bericht(f"THUMBS_DIR    : {THUMBS_DIR_NAME}")
    log_bericht(f"THUMBNAIL     : {cfg.get('THUMBNAIL')}")
    log_bericht(f"PICTURE       : {cfg.get('PICTURE') if cfg.get('PICTURE') else 'Original size (not resized)'}")
    log_bericht(f"EXCLUDED      : {cfg.get('EXCLUDED')}")
    log_bericht(f"RENAME        : {RENAME_FILES} (RC: {cfg.get('RENAME')})")
    log_bericht(f"DOWNLOAD      : {DOWNLOAD_PICTURES} (RC: {cfg.get('DOWNLOAD')})")
    log_bericht(f"REVERSE       : {REVERSE_ORDER} (RC: {cfg.get('REVERSE')})")
    log_bericht(f"DISABLE_EXIF  : {DISABLE_EXIF} (RC: {cfg.get('NO_EXIF')})")
    log_bericht(f"RCLONE        : {DO_RCLONE} (RC: {cfg.get('RCLONE')})")
    if DO_RCLONE and rclone_src:
        log_bericht(f"  RCLONE_SRC  : {rclone_src}")
        log_bericht(f"  RCLONE_DST  : {rclone_dst}")
    log_bericht(f"COLUMNS       : {cfg.get('COLUMNS')}")
    log_bericht(f"ROWS          : {cfg.get('ROWS')}")
    log_bericht(f"WATERMARK     : '{WATERMARK}'")
    if WATERMARK:
        log_bericht(f"  WM_FONT       : {WM_FONT}")
        log_bericht(f"  WM_SIZE       : {WM_SIZE}")
        log_bericht(f"  WM_ICON_SIZE  : {WM_ICON_SIZE}")
        log_bericht(f"  WM_TRANSPARANCY: {cfg.get('WM_TRANSPARANCY')}")
        log_bericht(f"  WM_LOCATION   : {cfg.get('WM_LOCATION')}")
        log_bericht(f"  WM_ALLIGNMENT : {cfg.get('WM_ALLIGNMENT')}")
    log_bericht(f"FOOTER        : '{cfg.get('FOOTER')}'")
    log_bericht(f"  (Preview)   : {footer_preview}")
    if HAS_PIL:
        try:
            from PIL import __version__ as pil_ver
            log_bericht(f"Pillow    : ✓ (v{pil_ver})")
        except Exception:
            log_bericht("Pillow    : ✓")
        if HAS_HEIF:
            try:
                import pillow_heif
                log_bericht(f"HEIC/HEIF : ✓ (pillow-heif v{pillow_heif.__version__})")
            except Exception:
                log_bericht("HEIC/HEIF : ✓")
        else:
            log_bericht("HEIC/HEIF : ✗ not found — install with: pip install pillow-heif")
    else:
        log_bericht("Pillow    : ✗ not found — install with: pip install Pillow")
        log_bericht("            Without Pillow, original files will be used as thumbnails.")
    # Genereer en schrijf html-album.css naar de output directory
    try:
        (OUTPUT_DIR / "html-album.css").write_text(get_css(), encoding="utf-8")
        log_bericht(f"CSS       : ✓ html-album.css updated in {OUTPUT_DIR}")
    except Exception as exc:
        log_bericht(f"CSS       : ✗ Error writing html-album.css: {exc}")

    # Kopieer het icoon als het bestaat naar de output directory
    target_icon_name = Path(ICON_FILE_NAME).name
    pingu_src = SCRIPT_DIR / target_icon_name
    search_dirs = [SCRIPT_DIR, Path(__file__).resolve().parent]
    if SOURCE_DIR and SOURCE_DIR.exists():
        search_dirs.append(SOURCE_DIR)
    if sys.platform != "win32":
        search_dirs.extend([Path.home() / "html-album", Path.home() / "scripts", Path.home() / "etc"])

    found_icon = None
    for sdir in search_dirs:
        if not sdir.exists():
            continue
        candidate = sdir / target_icon_name
        if candidate.exists():
            found_icon = candidate
            break
        for f in sdir.iterdir():
            if f.is_file() and is_icon_file(f):
                found_icon = f
                break
        if found_icon and found_icon.exists():
            break

    if found_icon:
        pingu_src = found_icon

    if pingu_src.exists():
        if pingu_src.name != target_icon_name and not (pingu_src.parent / target_icon_name).exists():
            try:
                restored = pingu_src.parent / target_icon_name
                pingu_src.rename(restored)
                pingu_src = restored
                log_bericht(f"Icoon     : ✓ Hersteld naar {target_icon_name}")
            except Exception:
                pass
        try:
            safe_copy(pingu_src, OUTPUT_DIR / target_icon_name)
            log_bericht(f"Icoon     : ✓ {target_icon_name} copied to {OUTPUT_DIR}")
        except Exception as exc:
            log_bericht(f"Icoon     : ✗ Error copying {target_icon_name}: {exc}")

    log_bericht("─" * 36)
    time.sleep(1)

    process_dir(target_src_dir, target_out_dir, parent_index, root_title)

    log_bericht("\n" + "═" * 36)
    log_bericht("✅  Album generated!")
    log_bericht(f"    Open: {OUTPUT_DIR / INDEX_FILE_NAME}")
    log_bericht("═" * 36)

if __name__ == "__main__":
    main()
