#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
html-album.py — HTML Fotoalbum Generator
Genereert een HTML-album vergelijkbaar met alm.agrarix.net

Vereisten:
    pip install Pillow

Gebruik:
    python html-album.py
    (leest html-album.json in dezelfde map)
"""

import argparse
import json
import os
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path

# Forceer UTF-8 output zodat cmd/PowerShell niet crasht op speciale tekens
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Programma details voor de footer
PGM = "html-album"
VERSION = "2.0 (30-06-2026 08:52)"

def safe_copy(src: Path, dst: Path) -> None:
    """Kopieert een bestand. Probeert metadata te behouden (copy2), maar valt terug op copyfile bij OS-fouten (zoals op netwerkshares)."""
    try:
        shutil.copy2(src, dst)
    except OSError:
        shutil.copyfile(src, dst)


# ---------------------------------------------------------------------------
# Pillow (voor thumbnails)
# ---------------------------------------------------------------------------
try:
    from PIL import Image, ExifTags, ImageOps
    HAS_PIL = True
except ImportError:
    HAS_PIL = False

# ---------------------------------------------------------------------------
# Argumenten en configuratie inlezen
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).parent

# Windows-stijl /help en /? mappen naar --help voor argparse
for _i, _arg in enumerate(sys.argv):
    if _arg.lower() in ("/help", "/?", "?"):
        sys.argv[_i] = "--help"

parser = argparse.ArgumentParser(
    prog="html-album",
    description="Generates a static HTML photo album from a directory of JPEG images."
)
parser.add_argument(
    "config_file",
    nargs="?",
    default="html-album.rc",
    help="Path to the configuration file (default: %(default)s)"
)
parser.add_argument(
    "-V", "--version",
    action="version",
    version=f"%(prog)s {VERSION}",
    help="Show the program's version number and exit"
)
parser.add_argument(
    "-a", "--all",
    action="store_true",
    help="Force regeneration of all images and thumbnails"
)
parser.add_argument(
    "-r", "--reverse",
    action="store_true",
    help="Reversed order of folders and images (reverse)"
)
parser.add_argument(
    "--rename",
    action="store_true",
    help="Rename picture filenames to YYMMDD_HHMMSS-<orig-name> in output"
)

args = parser.parse_args()
config_naam = args.config_file
FORCE_ALL = args.all
REVERSE_ORDER = args.reverse
CLI_RENAME = args.rename

CONFIG_FILE = Path(config_naam)
if not CONFIG_FILE.is_absolute():
    if sys.platform != "win32":
        CONFIG_FILE = Path.home() / "etc" / config_naam
    else:
        CONFIG_FILE = SCRIPT_DIR / CONFIG_FILE


DEFAULTS = {
    "PICTURES_DIR": "pictures",
    "THUMBS_DIR": "thumbs",
    "EXCLUDED": ["res"],
    "THUMBNAIL": "140x140",
    "PICTURE": "",
    "SOURCE_DIR": "",
    "OUTPUT_DIR": "",
    "INDEX_FILE": "index.html",
    "LOG_FILE": "html-album.log",
    "COLUMNS": "0",
    "ROWS": "0",
    "FOOTER": "Generated by (Agrarix)${PGM} v${VER} ${DATE} ${TIME}",
    "RENAME": "false",
    "WATERMARK": "",
    "WM_FONT": "Verdana",
    "WM_SIZE": "12",
    "WM_TRANSPARANCY": "80%",
    "WM_LOCATION": "90",
}


def _laad_config(pad: Path) -> dict:
    """Lees html-album.rc met KEY="VALUE" syntax."""
    config = {}
    try:
        with open(pad, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, val = line.split("=", 1)
                    key = key.strip()
                    val = val.strip()
                    if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
                        val = val[1:-1]
                    if key == "EXCLUDED":
                        val = val.replace("[", "").replace("]", "").replace('"', '').replace("'", "")
                        config[key] = [x.strip() for x in val.split(",") if x.strip()]
                    else:
                        config[key] = val
        return config
    except Exception as e:
        print(f"ERROR loading {CONFIG_FILE.name}: {e}")
        sys.exit(1)

if CONFIG_FILE.exists():
    cfg = {**DEFAULTS, **_laad_config(CONFIG_FILE)}
else:
    print(f"{CONFIG_FILE.name} not found, using default values.")
    cfg = DEFAULTS

RENAME_FILES = CLI_RENAME or cfg.get("RENAME", "false").lower() in ("true", "1", "yes")

PICTURES_DIR_NAME: str = cfg.get("PICTURES_DIR", cfg.get("SLIDES_DIR", "pictures"))
THUMBS_DIR_NAME: str = cfg["THUMBS_DIR"]
INDEX_FILE_NAME: str = cfg["INDEX_FILE"]
SOURCE_DIR_RAW = os.path.expandvars(cfg["SOURCE_DIR"]) if cfg["SOURCE_DIR"] else ""
OUTPUT_DIR_RAW = os.path.expandvars(cfg["OUTPUT_DIR"]) if cfg["OUTPUT_DIR"] else ""
SOURCE_DIR = Path(SOURCE_DIR_RAW.replace("\\", "/")) if SOURCE_DIR_RAW else Path()
OUTPUT_DIR = Path(OUTPUT_DIR_RAW.replace("\\", "/")) if OUTPUT_DIR_RAW else Path()

try:
    _w, _h = map(int, cfg["THUMBNAIL"].lower().split("x"))
    THUMB_SIZE = (_w, _h)
except ValueError:
    THUMB_SIZE = (140, 140)

PICTURE_SIZE = None
if cfg.get("PICTURE"):
    try:
        _wp, _hp = map(int, cfg["PICTURE"].lower().split("x"))
        PICTURE_SIZE = (_wp, _hp)
    except ValueError:
        pass

# Watermark configuratie
WATERMARK = cfg.get("WATERMARK", "").strip()
WM_FONT = cfg.get("WM_FONT", "Verdana").strip()

try:
    _wm_size_raw = cfg.get("WM_SIZE", "12").split("#")[0].strip()
    WM_SIZE = int(_wm_size_raw)
except ValueError:
    WM_SIZE = 12

try:
    _wm_trans_raw = cfg.get("WM_TRANSPARANCY", "80%").split("#")[0].strip()
    if _wm_trans_raw.endswith("%"):
        WM_TRANSPARANCY = float(_wm_trans_raw[:-1]) / 100.0
    else:
        WM_TRANSPARANCY = float(_wm_trans_raw)
        if WM_TRANSPARANCY > 1.0:
            WM_TRANSPARANCY /= 100.0
except ValueError:
    WM_TRANSPARANCY = 0.80

try:
    _wm_loc_raw = cfg.get("WM_LOCATION", "90").split("#")[0].strip()
    WM_LOCATION = float(_wm_loc_raw)
except ValueError:
    WM_LOCATION = 90.0


EXCLUDED: set[str] = {
    x.lower() for x in (
        set(cfg["EXCLUDED"]) |
        {PICTURES_DIR_NAME, THUMBS_DIR_NAME, "pictures", "slides", "thumbs", "slides_dir", "thumbs_dir", "pictures_dir"}
    )
}
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".gif"}

# Bepaal het logbestand-pad. Als het een relatieve bestandsnaam is, zet het in SCRIPT_DIR (applicatie-root).
cfg_log_file = os.path.expandvars(cfg.get("LOG_FILE", "html-album.log"))
if Path(cfg_log_file).is_absolute():
    LOG_FILE_PATH = Path(cfg_log_file.replace("\\", "/"))
else:
    LOG_FILE_PATH = SCRIPT_DIR / cfg_log_file

# Globale log-bestand handler
# (Wordt geïnitialiseerd in main)

def log_bericht(bericht: str) -> None:
    """Schrijft naar stdout én naar het logbestand html-album.log."""
    # Print direct naar het scherm (UTF-8)
    print(bericht)
    sys.stdout.flush()
    
    # Schrijf naar logbestand in de uitvoermap (indien geconfigureerd en beschikbaar)
    if LOG_FILE_PATH:
        try:
            with open(LOG_FILE_PATH, "a", encoding="utf-8") as lf:
                # Strip eventuele ansi-achtige tekens of print gewoon platte tekst
                schoon_bericht = bericht.replace("\U0001f4c2", "[DIR]").replace("\u2713", "[OK]").replace("\u2705", "[DONE]")
                lf.write(f"[{datetime.now().strftime('%H:%M:%S')}] {schoon_bericht}\n")
        except Exception:
            pass

def get_css() -> str:
    tw, th = THUMB_SIZE
    cell_w = tw + 10
    
    cols = int(cfg.get("COLUMNS", 0))
    if cols > 0:
        page_max_w = max(880, cell_w * cols + 40)
    else:
        page_max_w = max(880, cell_w * 2 + 40)
    
    css_path = SCRIPT_DIR / "html-album.css"
    if css_path.exists():
        css_res = css_path.read_text(encoding="utf-8")
    else:
        log_bericht("    ⚠ Warning: html-album.css not found in script directory! Minimal fallback styling will be used.")
        if sys.stdin.isatty():
            try:
                antwoord = input("    Press [Enter] to continue, or 'q' to stop: ").strip().lower()
                if antwoord == 'q':
                    log_bericht("    Generation aborted by user.")
                    sys.exit(0)
            except (EOFError, KeyboardInterrupt):
                pass
        css_res = "* { box-sizing: border-box; }"
    
    css_res = css_res.replace("max-width: 880px;", f"max-width: {page_max_w}px;")
    css_res = css_res.replace("width: 148px;", f"width: {cell_w}px;")
    css_res = css_res.replace("width: 138px;", f"width: {tw}px;")
    css_res = css_res.replace("height: 112px;", f"height: {th}px;")
    css_res = css_res.replace("max-width: 138px;", f"max-width: {tw}px;")
    css_res = css_res.replace("max-height: 112px;", f"max-height: {th}px;")
    css_res = css_res.replace("line-height: 112px;", f"line-height: {th}px;")
    
    if cols > 0:
        css_res += f"\n@media (max-width: 600px) {{\n    .thumb-grid {{\n        display: grid;\n        grid-template-columns: repeat({cols}, {cell_w}px);\n    }}\n}}\n"
    
    if th > 140:
        folder_font_size = min(120, int(th * 0.5))
        css_res = css_res.replace("font-size: 64px;", f"font-size: {folder_font_size}px;")
        
    return css_res

# ---------------------------------------------------------------------------
# Controleer of thumbnail opnieuw gegenereerd moet worden
# ---------------------------------------------------------------------------
def needs_thumbnail_regeneration(thumb_path: Path, src_path: Path) -> bool:
    if FORCE_ALL:
        return True
    if not thumb_path.exists():
        return True
    if not HAS_PIL:
        return False
    try:
        if src_path.stat().st_mtime > thumb_path.stat().st_mtime:
            return True
    except Exception:
        pass
    try:
        tw, th = THUMB_SIZE
        with Image.open(thumb_path) as img:
            # Als de thumbnail kleiner is dan de ingestelde THUMB_SIZE,
            # maar de bronfoto groter is dan de thumbnail, moet hij opnieuw
            with Image.open(src_path) as src_img:
                if (img.width < tw and img.height < th) and (src_img.width > img.width or src_img.height > img.height):
                    return True
            return not (img.width == tw or img.height == th or (img.width < tw and img.height < th))
    except Exception:
        return True

# ---------------------------------------------------------------------------
# Thumbnail maken met Pillow (bijgesneden vulling)
# ---------------------------------------------------------------------------
def make_thumbnail(src: Path, dst: Path) -> None:
    if not HAS_PIL:
        try:
            safe_copy(src, dst)
        except Exception as e:
            log_bericht(f"    ⚠  Could not copy file as thumbnail fallback: {e}")
        return
    try:
        with Image.open(src) as img:
            img = ImageOps.exif_transpose(img)
            img = img.convert("RGB")
            img.thumbnail(THUMB_SIZE, Image.LANCZOS)
            img.save(dst, "JPEG", quality=85, optimize=True)
    except PermissionError as pe:
        log_bericht(f"    ⚠  Access denied (file in use) while creating thumbnail for '{src.name}': {pe}")
    except Exception as exc:
        log_bericht(f"    ⚠  Thumbnail generation failed for '{src.name}': {exc}")
        try:
            safe_copy(src, dst)
        except Exception:
            pass

# ---------------------------------------------------------------------------
# Controleer of afbeelding opnieuw verkleind/gekopieerd moet worden
# ---------------------------------------------------------------------------
def needs_image_regeneration(dst_path: Path, src_path: Path) -> bool:
    if FORCE_ALL:
        return True
    if not dst_path.exists():
        return True
    try:
        if src_path.stat().st_mtime > dst_path.stat().st_mtime:
            return True
    except Exception:
        pass
    
    if HAS_PIL and PICTURE_SIZE:
        try:
            with Image.open(dst_path) as img:
                w, h = img.size
                pw, ph = PICTURE_SIZE
                if w > pw or h > ph:
                    return True
        except Exception:
            return True
    return False

# ---------------------------------------------------------------------------
# Grote afbeelding kopiëren/schalen met Pillow
# ---------------------------------------------------------------------------
def apply_watermark(img: Image.Image) -> Image.Image:
    """Voegt een semi-transparant watermerk toe aan de afbeelding."""
    if not WATERMARK:
        return img
        
    try:
        from PIL import ImageDraw, ImageFont
    except ImportError:
        return img

    try:
        # Maak een RGBA-laag voor het watermerk
        watermark_layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
        draw = ImageDraw.Draw(watermark_layer)
        
        # Probeer het geconfigureerde font te laden
        font = None
        font_paths = [
            WM_FONT,
            f"{WM_FONT}.ttf",
            f"{WM_FONT}.TTF",
        ]
        
        if sys.platform == "win32":
            font_paths.extend([
                f"C:\\Windows\\Fonts\\{WM_FONT}.ttf",
                f"C:\\Windows\\Fonts\\{WM_FONT}.TTF",
                f"C:\\Windows\\Fonts\\{WM_FONT}bd.ttf",
                "C:\\Windows\\Fonts\\arial.ttf",
            ])
        else:
            font_paths.extend([
                f"/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
                f"/usr/share/fonts/truetype/freefont/FreeSans.ttf",
                f"/usr/share/fonts/truetype/msttcorefonts/{WM_FONT}.ttf",
                f"/usr/share/fonts/truetype/msttcorefonts/{WM_FONT}.TTF",
            ])
            
        for path in font_paths:
            try:
                font = ImageFont.truetype(path, WM_SIZE)
                break
            except Exception:
                continue
                
        if font is None:
            font = ImageFont.load_default()
            
        # Bereken tekstafmetingen
        try:
            left, top, right, bottom = draw.textbbox((0, 0), WATERMARK, font=font)
            text_width = right - left
            text_height = bottom - top
        except AttributeError:
            text_width, text_height = draw.textsize(WATERMARK, font=font)
            
        # Bereken X (gecentreerd) en Y (op basis van WM_LOCATION percentage)
        x = (img.width - text_width) // 2
        y = int(img.height * WM_LOCATION / 100) - (text_height // 2)
        
        x = max(0, min(x, img.width - text_width))
        y = max(0, min(y, img.height - text_height))
        
        opacity = 1.0 - WM_TRANSPARANCY
        alpha = int(255 * max(0.0, min(1.0, opacity)))
        
        color = (255, 255, 255, alpha)
        draw.text((x, y), WATERMARK, font=font, fill=color)
        
        img_rgba = img.convert("RGBA")
        combined = Image.alpha_composite(img_rgba, watermark_layer)
        return combined.convert("RGB")
    except Exception as e:
        log_bericht(f"    ⚠  Fout bij toepassen watermerk: {e}")
        return img

def make_resized_image(src: Path, dst: Path) -> None:
    if not HAS_PIL or not PICTURE_SIZE:
        try:
            safe_copy(src, dst)
        except Exception as e:
            log_bericht(f"    ⚠  Could not copy file: {e}")
        return
    try:
        with Image.open(src) as img:
            img = ImageOps.exif_transpose(img)
            img = img.convert("RGB")
            img.thumbnail(PICTURE_SIZE, Image.LANCZOS)
            
            if WATERMARK:
                img = apply_watermark(img)
                
            img.save(dst, "JPEG", quality=85, optimize=True)
    except PermissionError as pe:
        log_bericht(f"    ⚠  Access denied (file in use) while creating image for '{src.name}': {pe}")
    except Exception as exc:
        log_bericht(f"    ⚠  Resizing failed for '{src.name}': {exc}")
        try:
            safe_copy(src, dst)
        except Exception:
            pass

def get_exif_data(img_path: Path) -> dict:
    if not HAS_PIL:
        return {}
    try:
        with Image.open(img_path) as img:
            exif = img._getexif()
            if not exif:
                return {}
            data = {}
            for tag, val in exif.items():
                tag_name = ExifTags.TAGS.get(tag, tag)
                data[tag_name] = val
            return data
    except Exception:
        return {}

def get_formatted_exif(img_path: Path) -> str:
    raw_exif = get_exif_data(img_path)
    if not raw_exif:
        return ""
    
    parts = []
    
    # Camera model
    make = raw_exif.get("Make", "")
    model = raw_exif.get("Model", "")
    if model:
        model_str = str(model).strip()
        make_str = str(make).strip()
        if make_str and make_str.lower() not in model_str.lower():
            parts.append(f"📷 {make_str} {model_str}")
        else:
            parts.append(f"📷 {model_str}")
            
    # Datum / Tijd
    dt_orig = raw_exif.get("DateTimeOriginal")
    if dt_orig:
        try:
            dt = datetime.strptime(str(dt_orig).strip(), "%Y:%m:%d %H:%M:%S")
            parts.append(f"📅 {dt.strftime('%d-%m-%Y %H:%M')}")
        except Exception:
            parts.append(f"📅 {str(dt_orig).strip()}")
            
    # Belichtingsinstellingen (Aperture, Shutter, ISO, Focal Length)
    settings = []
    
    # Brandpuntsafstand
    focal = raw_exif.get("FocalLength")
    if focal is not None:
        try:
            if isinstance(focal, tuple) and len(focal) == 2:
                f_val = focal[0] / focal[1]
            else:
                f_val = float(focal)
            settings.append(f"{f_val:.0f}mm")
        except Exception:
            pass
            
    # Diafragma
    fnum = raw_exif.get("FNumber")
    if fnum is not None:
        try:
            if isinstance(fnum, tuple) and len(fnum) == 2:
                fn_val = fnum[0] / fnum[1]
            else:
                fn_val = float(fnum)
            settings.append(f"f/{fn_val:.1f}" if fn_val % 1 != 0 else f"f/{fn_val:.0f}")
        except Exception:
            pass
            
    # Sluitertijd
    exp = raw_exif.get("ExposureTime")
    if exp is not None:
        try:
            if isinstance(exp, tuple) and len(exp) == 2:
                num, den = exp
                if num == 1:
                    settings.append(f"1/{den}s")
                elif num > 1:
                    settings.append(f"{num/den:.1f}s")
                else:
                    settings.append(f"{num}/{den}s")
            else:
                exp_val = float(exp)
                if exp_val < 1.0:
                    recip = round(1.0 / exp_val)
                    settings.append(f"1/{recip}s")
                else:
                    settings.append(f"{exp_val:.1f}s")
        except Exception:
            pass
            
    # ISO
    iso = raw_exif.get("ISOSpeedRatings")
    if iso is not None:
        settings.append(f"ISO {iso}")
        
    if settings:
        parts.append("⚙️ " + " | ".join(settings))
        
    return "  •  ".join(parts)

def get_rename_prefix(img_path: Path) -> str:
    """Haalt de EXIF datum-tijd (of mtime) op en returnt YYMMDD_HHMMSS-."""
    exif = get_exif_data(img_path)
    dt_orig = exif.get("DateTimeOriginal")
    if dt_orig:
        try:
            dt = datetime.strptime(str(dt_orig).strip(), "%Y:%m:%d %H:%M:%S")
            return dt.strftime("%y%m%d_%H%M%S-")
        except Exception:
            pass
    try:
        mtime = img_path.stat().st_mtime
        dt = datetime.fromtimestamp(mtime)
        return dt.strftime("%y%m%d_%H%M%S-")
    except Exception:
        return ""

def get_new_filename(img_path: Path) -> str:
    orig_name = img_path.name
    if not RENAME_FILES:
        return orig_name
    if re.match(r"^\d{6}_\d{6}-", orig_name):
        return orig_name
    prefix = get_rename_prefix(img_path)
    return f"{prefix}{orig_name}"

# ---------------------------------------------------------------------------
# Genereer HTML voor één slide-pagina
# ---------------------------------------------------------------------------
def generate_slide_html(
    out_file: Path,
    img_fname: str,
    prev_slide: str,
    next_slide: str,
    index_href: str,
    slide_breadcrumb_html: str,
    src_img_path: Path,
    css_href: str,
) -> None:
    prev_js = f'"{prev_slide}"' if prev_slide else "null"
    next_js = f'"{next_slide}"' if next_slide else "null"

    svg_left = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" style="display: inline-block; vertical-align: middle;"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>'
    svg_right = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" style="display: inline-block; vertical-align: middle;"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>'

    prev_btn = f'<span class="nav-btn prev-btn disabled" title="No previous picture">{svg_left}</span>'
    next_btn = f'<span class="nav-btn next-btn disabled" title="No next picture">{svg_right}</span>'
    if prev_slide:
        prev_btn = f'<a href="{prev_slide}" class="nav-btn prev-btn" title="Previous picture (&#8592;)">{svg_left}</a>'
    if next_slide:
        next_btn = f'<a href="{next_slide}" class="nav-btn next-btn" title="Next picture (&#8594;)">{svg_right}</a>'

    exif_str = get_formatted_exif(src_img_path)
    exif_html = f'<div class="slide-exif">{exif_str}</div>' if exif_str else ""

    img_src = img_fname if PICTURE_SIZE else f"../{img_fname}"

    svg_up = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" style="display: inline-block; vertical-align: middle;"><line x1="12" y1="19" x2="12" y2="5"></line><polyline points="5 12 12 5 19 12"></polyline></svg>'

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{img_fname}</title>
    <link rel="stylesheet" href="{css_href}">
</head>
<body>
<div class="page-wrap">
    <div class="album-header">
        <a href="{index_href}" class="nav-btn up-btn" title="Back to album (Esc)">{svg_up}</a>
        <span class="header-title">{slide_breadcrumb_html}</span>
        <div class="header-nav">
            {prev_btn}
            {next_btn}
        </div>
    </div>
    <div class="slide-wrap">
        <img src="{img_src}" alt="{img_fname}" class="slide-image">
        <div class="slide-info">{img_fname}</div>
        {exif_html}
    </div>
</div>
<script>
var prevSlide = {prev_js};
var nextSlide = {next_js};
document.addEventListener('keydown', function(e) {{
    switch (e.key) {{
        case 'ArrowLeft':  case 'a': case 'A':
            if (prevSlide) window.location = prevSlide; break;
        case 'ArrowRight': case 'd': case 'D': case ' ':
            if (nextSlide) window.location = nextSlide; break;
        case 'Backspace':  case 'Escape': case 'u': case 'U':
            window.location = '{index_href}'; break;
    }}
}});
</script>
</body>
</html>
"""
    out_file.write_text(html, encoding="utf-8")

# ---------------------------------------------------------------------------
# Genereer index.html voor één map
# ---------------------------------------------------------------------------
def generate_index_html(
    index_file: Path,
    title: str,
    breadcrumb_html: str,
    up_href: str,
    src_dir: Path,
    out_dir: Path,
    css_href: str,
) -> None:
    generated_date = datetime.now().strftime("%d-%m-%Y %H:%M")

    up_btn = ""
    if up_href:
        svg_up = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" style="display: inline-block; vertical-align: middle;"><line x1="12" y1="19" x2="12" y2="5"></line><polyline points="5 12 12 5 19 12"></polyline></svg>'
        up_btn = f'<a href="{up_href}" class="nav-btn up-btn" title="Up to parent directory">{svg_up}</a>'

    images = sorted(
        [f for f in src_dir.iterdir() if f.is_file() and f.suffix.lower() in IMAGE_EXTS],
        key=lambda f: f.name.lower(),
        reverse=REVERSE_ORDER,
    )

    img_cells: list[str] = []
    for i, img in enumerate(images):
        fname       = get_new_filename(img)
        name_no_ext = Path(fname).stem
        thumb_rel   = f"{THUMBS_DIR_NAME}/{name_no_ext}_thumb.jpg"
        slide_rel   = f"{PICTURES_DIR_NAME}/{name_no_ext}.html"
        
        is_map_foto = (i == 0)
        cell_class = "thumb-cell map-foto" if is_map_foto else "thumb-cell"
        title_text = f"{fname} [folder cover]" if is_map_foto else fname
        label_text = f"\U0001f4c1 {fname}" if is_map_foto else fname
        
        img_cells.append(
            f'        <div class="{cell_class}">\n'
            f'            <a href="{slide_rel}" title="{title_text}">\n'
            f'                <div class="thumb-img-wrap">\n'
            f'                    <img src="{thumb_rel}" alt="{fname}" loading="lazy">\n'
            f'                </div>\n'
            f'                <div class="thumb-label">{label_text}</div>\n'
            f'            </a>\n'
            f'        </div>'
        )

    subdirs = sorted(
        [d for d in src_dir.iterdir() if d.is_dir() and d.name.lower() not in EXCLUDED],
        key=lambda d: d.name.lower(),
        reverse=REVERSE_ORDER,
    )

    dir_cells: list[str] = []
    for subdir in subdirs:
        dname            = subdir.name

        first_img = next(
            (f for f in sorted(subdir.iterdir(), key=lambda x: x.name.lower(), reverse=REVERSE_ORDER) if f.is_file() and f.suffix.lower() in IMAGE_EXTS),
            None,
        )

        if first_img:
            first_img_stem = Path(get_new_filename(first_img)).stem
            folder_thumb_dst = out_dir / THUMBS_DIR_NAME / f"folder_{dname}_{first_img_stem}_thumb.jpg"
            if needs_thumbnail_regeneration(folder_thumb_dst, first_img):
                make_thumbnail(first_img, folder_thumb_dst)
                log_bericht(f"    ✓ Folder '{dname}' ({THUMBS_DIR_NAME}/ with photo: {first_img.name})")
            else:
                log_bericht(f"    ✓ Folder '{dname}' (unchanged, photo: {first_img.name})")
            thumb_tag = f'<img src="{THUMBS_DIR_NAME}/folder_{dname}_{first_img_stem}_thumb.jpg" alt="{dname}" loading="lazy">'
            label = f"\U0001f4c1 {dname}"
        else:
            thumb_tag = '<div class="folder-icon">\U0001f4c1</div>'
            label     = dname

        dir_cells.append(
            f'        <div class="thumb-cell folder">\n'
            f'            <a href="{dname}/{INDEX_FILE_NAME}" title="{dname}">\n'
            f'                <div class="thumb-img-wrap">\n'
            f'                    {thumb_tag}\n'
            f'                </div>\n'
            f'                <div class="thumb-label">{label}</div>\n'
            f'            </a>\n'
            f'        </div>'
        )

    all_cells = "\n".join(img_cells + dir_cells)

    # Formateer datum en tijd
    now = datetime.now()
    date_str = now.strftime("%d-%m-%Y")
    time_str = now.strftime("%H:%M")

    footer_tmpl = cfg.get("FOOTER", "Generated by (Agrarix)${PGM} v${VER} ${DATE} ${TIME}")
    footer_text = footer_tmpl
    footer_text = footer_text.replace("${PGM}", PGM).replace("{PGM}", PGM)
    footer_text = footer_text.replace("${VER}", VERSION).replace("{VER}", VERSION).replace("{VERSION}", VERSION)
    footer_text = footer_text.replace("${DATE}", date_str).replace("{date_str}", date_str)
    footer_text = footer_text.replace("${TIME}", time_str).replace("{time_str}", time_str)

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="photoalbum,gallery,photo,online">
    <title>{title}</title>
    <link rel="stylesheet" href="{css_href}">
</head>
<body>
<div class="page-wrap">
    <div class="album-header">
        {up_btn}
        <span class="header-title">{breadcrumb_html}</span>
    </div>
    <div class="thumb-grid">
{all_cells}
    </div>
    <div class="footer">{footer_text}</div>
</div>
</body>
</html>
"""
    index_file.write_text(html, encoding="utf-8")

# ---------------------------------------------------------------------------
# Recursieve mapverwerking
# ---------------------------------------------------------------------------
def process_dir(
    src_dir: Path,
    out_dir: Path,
    parent_index: str,
    title: str,
) -> None:
    log_bericht(f"\U0001f4c2  {title}")
    log_bericht(f"    source : {src_dir}")
    log_bericht(f"    output : {out_dir}")

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / PICTURES_DIR_NAME).mkdir(exist_ok=True)
    (out_dir / THUMBS_DIR_NAME).mkdir(exist_ok=True)

    images = sorted(
        [f for f in src_dir.iterdir() if f.is_file() and f.suffix.lower() in IMAGE_EXTS],
        key=lambda f: f.name.lower(),
        reverse=REVERSE_ORDER,
    )
    log_bericht(f"    photos : {len(images)}")

    # Bereken relatieve pad naar OUTPUT_DIR root voor CSS link
    rel_parts = [p for p in out_dir.relative_to(OUTPUT_DIR).parts if p not in ('.', '/')]
    relative_path_to_root = "../" * len(rel_parts)
    
    version_str = datetime.now().strftime("%Y%m%d%H%M%S")
    index_css_href = f"{relative_path_to_root}html-album.css?v={version_str}"
    slide_css_href = f"../{relative_path_to_root}html-album.css?v={version_str}"

    # Bouw kruimelpad (breadcrumbs)
    rel_path = src_dir.relative_to(SOURCE_DIR)
    root_name = SOURCE_DIR.name
    root_display = f"Photo album : {root_name}"
    
    if rel_path == Path('.'):
        breadcrumb_html = f'<a href="{INDEX_FILE_NAME}">{root_display}</a>'
        slide_breadcrumb_html = f'<a href="../{INDEX_FILE_NAME}">{root_display}</a>'
    else:
        links = []
        slide_links = []
        depth = len(rel_path.parts)
        slide_depth = depth + 1
        
        # Voor indexpagina's
        links.append(f'<a href="{"../" * depth}{INDEX_FILE_NAME}">{root_name}</a>')
        for idx, part_name in enumerate(rel_path.parts[:-1]):
            steps_up = depth - 1 - idx
            links.append(f'<a href="{"../" * steps_up}{INDEX_FILE_NAME}">{part_name}</a>')
        links.append(f'<a href="{INDEX_FILE_NAME}">{rel_path.parts[-1]}</a>')
        breadcrumb_html = " / ".join(links)
        
        # Voor slidepagina's (één niveau dieper wegens slides/ submap)
        slide_links.append(f'<a href="{"../" * slide_depth}{INDEX_FILE_NAME}">{root_name}</a>')
        for idx, part_name in enumerate(rel_path.parts[:-1]):
            steps_up = slide_depth - 1 - idx
            slide_links.append(f'<a href="{"../" * steps_up}{INDEX_FILE_NAME}">{part_name}</a>')
        slide_links.append(f'<a href="../{INDEX_FILE_NAME}">{rel_path.parts[-1]}</a>')
        slide_breadcrumb_html = " / ".join(slide_links)

    # Bepaal target bestandsnamen voor alle afbeeldingen in deze directory
    mapped_images = []
    for img in images:
        target_name = get_new_filename(img)
        target_stem = Path(target_name).stem
        mapped_images.append((img, target_name, target_stem))

    for i, (img, fname, name_no_ext) in enumerate(mapped_images):
        actions     = []

        # Kopieer of hernoem het origineel naar de uitvoermap
        dst_img = out_dir / fname
        if dst_img != img:
            if img.parent == dst_img.parent:
                # Bron- en doelmap zijn hetzelfde: fysiek hernoemen
                if not dst_img.exists():
                    try:
                        img.rename(dst_img)
                        img = dst_img  # Update img naar het nieuwe pad voor thumbnails/exif
                        actions.append("renamed")
                    except Exception as e:
                        log_bericht(f"    ⚠  Error renaming '{img.name}' to '{fname}': {e}")
                else:
                    # Als de hernoemde versie al bestaat, update het pad naar het bestaande bestand
                    img = dst_img
            else:
                # Bron- en doelmap zijn verschillend: kopiëren
                if not dst_img.exists():
                    try:
                        safe_copy(img, dst_img)
                        actions.append("./")
                    except PermissionError as pe:
                        log_bericht(f"    ⚠  Permission denied copying '{fname}': {pe}")
                    except Exception as e:
                        log_bericht(f"    ⚠  Error copying '{fname}': {e}")

        # Genereer verkleinde versie in pictures/ indien PICTURE_SIZE is ingesteld
        if PICTURE_SIZE:
            dst_resized = out_dir / PICTURES_DIR_NAME / fname
            if needs_image_regeneration(dst_resized, img):
                make_resized_image(img, dst_resized)
                actions.append(f"{PICTURES_DIR_NAME}/")

        thumb = out_dir / THUMBS_DIR_NAME / f"{name_no_ext}_thumb.jpg"
        if needs_thumbnail_regeneration(thumb, img):
            make_thumbnail(img, thumb)
            actions.append(f"{THUMBS_DIR_NAME}/")

        prev_slide = mapped_images[i - 1][2] + ".html" if i > 0 else ""
        next_slide = mapped_images[i + 1][2] + ".html" if i < len(mapped_images) - 1 else ""

        generate_slide_html(
            out_dir / PICTURES_DIR_NAME / f"{name_no_ext}.html",
            fname,
            prev_slide,
            next_slide,
            f"../{INDEX_FILE_NAME}",
            slide_breadcrumb_html,
            img,
            slide_css_href,
        )
        
        is_map_foto = " [folder cover]" if i == 0 else ""
        if actions:
            log_bericht(f"    ✓ {fname} ({', '.join(actions)}){is_map_foto}")
        else:
            log_bericht(f"    ✓ {fname} (unchanged){is_map_foto}")

    generate_index_html(
        out_dir / INDEX_FILE_NAME,
        title,
        breadcrumb_html,
        parent_index,
        src_dir,
        out_dir,
        index_css_href,
    )

    subdirs = sorted(
        [d for d in src_dir.iterdir() if d.is_dir() and d.name.lower() not in EXCLUDED],
        key=lambda d: d.name.lower(),
        reverse=REVERSE_ORDER,
    )
    for subdir in subdirs:
        process_dir(
            subdir,
            out_dir / subdir.name,
            f"../{INDEX_FILE_NAME}",
            subdir.name,
        )

# ---------------------------------------------------------------------------
# Startpunt
# ---------------------------------------------------------------------------
def main() -> None:
    global LOG_FILE_PATH
    
    if not SOURCE_DIR or not SOURCE_DIR.exists():
        print(f"\n❌ Source directory not found: {SOURCE_DIR}")
        print("   Adjust SOURCE_DIR in html-album.rc")
        sys.exit(1)

    if not OUTPUT_DIR or str(OUTPUT_DIR) in ("", "."):
        print("\n❌ OUTPUT_DIR is not set in html-album.rc")
        sys.exit(1)
        
    # Maak output directory alvast aan voor logbestand
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if LOG_FILE_PATH:
        LOG_FILE_PATH.parent.mkdir(parents=True, exist_ok=True)
        try:
            with open(LOG_FILE_PATH, "w", encoding="utf-8") as lf:
                lf.write(f"=== Album Generator Log {datetime.now().strftime('%d-%m-%Y %H:%M:%S')} ===\n")
        except Exception as exc:
            print(f"Kon logbestand niet maken op {LOG_FILE_PATH}: {exc}")

    # Formateer footer preview
    now = datetime.now()
    date_str = now.strftime("%d-%m-%Y")
    time_str = now.strftime("%H:%M")
    footer_tmpl = cfg.get("FOOTER", "Generated by (Agrarix)${PGM} v${VER} ${DATE} ${TIME}")
    footer_preview = footer_tmpl
    footer_preview = footer_preview.replace("${PGM}", PGM).replace("{PGM}", PGM)
    footer_preview = footer_preview.replace("${VER}", VERSION).replace("{VER}", VERSION).replace("{VERSION}", VERSION)
    footer_preview = footer_preview.replace("${DATE}", date_str).replace("{date_str}", date_str)
    footer_preview = footer_preview.replace("${TIME}", time_str).replace("{time_str}", time_str)

    log_bericht("HTML Photo Album Generator")
    log_bericht("─" * 36)
    log_bericht(f"Source    : {SOURCE_DIR}")
    log_bericht(f"Output    : {OUTPUT_DIR}")
    log_bericht(f"Log file  : {LOG_FILE_PATH}")
    log_bericht(f"Thumbnail : {THUMB_SIZE[0]}x{THUMB_SIZE[1]}")
    if FORCE_ALL:
        log_bericht("Mode      : Force regeneration of all (--all)")
    else:
        log_bericht("Mode      : Only new/modified files")
    if REVERSE_ORDER:
        log_bericht("Order     : Reversed (reverse)")
    if RENAME_FILES:
        log_bericht("Rename    : Yes, to YYMMDD_HHMMSS-<orig-name>")
    else:
        log_bericht("Rename    : No")
    if PICTURE_SIZE:
        log_bericht(f"Image     : {PICTURE_SIZE[0]}x{PICTURE_SIZE[1]}")
    else:
        log_bericht("Image     : Original size")
    log_bericht(f"Exclude   : {', '.join(sorted(EXCLUDED))}")
    if WATERMARK:
        log_bericht(f"Watermark : '{WATERMARK}' (Font: {WM_FONT}, Size: {WM_SIZE}, Transparency: {WM_TRANSPARANCY * 100:.0f}%, Location: {WM_LOCATION}%)")
    else:
        log_bericht("Watermark : None")
    log_bericht(f"Footer    : {footer_preview}")
    if HAS_PIL:
        try:
            from PIL import __version__ as pil_ver
            log_bericht(f"Pillow    : ✓ (v{pil_ver})")
        except Exception:
            log_bericht("Pillow    : ✓")
    else:
        log_bericht("Pillow    : ✗ not found — install with: pip install Pillow")
        log_bericht("            Without Pillow, original files will be used as thumbnails.")
    # Genereer en schrijf html-album.css naar de output directory
    try:
        (OUTPUT_DIR / "html-album.css").write_text(get_css(), encoding="utf-8")
        log_bericht(f"CSS       : ✓ html-album.css updated in {OUTPUT_DIR}")
    except Exception as exc:
        log_bericht(f"CSS       : ✗ Error writing html-album.css: {exc}")
    log_bericht("─" * 36)

    root_title = SOURCE_DIR.name
    process_dir(SOURCE_DIR, OUTPUT_DIR, "", root_title)

    log_bericht("\n" + "═" * 36)
    log_bericht("✅  Album generated!")
    log_bericht(f"    Open: {OUTPUT_DIR / INDEX_FILE_NAME}")
    log_bericht("═" * 36)

if __name__ == "__main__":
    main()
